# HyConEx + HyperLogic (DR-HyperCF) sur les jeux HyConEx / HyperLogic

Entraînement du modèle hybride (TabResNet HyConEx + règles / CF HyperLogic) calibré sur Dry Bean.

**Sources de données**
- `HyConEx/data/` : adult, audit, blobs, compas, german_credit, heloc, law, moons, moons_with_blob, wine
- `HyperLogic/data/` : cardio, disease, brca-n, brca-s

**Prétraitement**
- colonnes **continues** → MinMax + intervalles (quantiles) → bipolarisation
- colonnes **catégorielles** → one-hot → bipolarisation

Pour **chaque jeu** : métriques, contrefactuels et règles extraites.

In [1]:
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from IPython.display import Markdown, display

ROOT = Path.cwd().resolve().parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from nouveau_module import HybridDRConfig, HybridDRTrainer
from hyconex_hyperlogic_datasets import list_available_datasets
from tabular_mixed_preprocessing import TabularDatasetSplits, get_dataset_loaders

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Device:', device)
print('Racine projet:', ROOT.parent)
print('Jeux détectés:', list_available_datasets())

Device: cuda
Racine projet: D:\ecole\master 2\recherche\INN\projet
Jeux détectés: {'hyconex': ['adult', 'audit', 'blobs', 'compas', 'german_credit', 'heloc', 'law', 'moons', 'wine', 'moons_with_blob'], 'hyperlogic': ['cardio', 'disease', 'brca-n', 'brca-s']}

## Configuration

Par défaut, tous les CSV/TSV présents localement sont entraînés.
Tu peux restreindre la liste `DATASETS` ou activer `QUICK_RUN`.

In [2]:
ALL_LOADERS = get_dataset_loaders()

# None = tous les jeux disponibles ; sinon liste explicite, ex. ['hyconex/adult', 'hyperlogic/cardio']
DATASETS = None

if DATASETS is None:
    DATASETS = sorted(ALL_LOADERS.keys())

SEED = 42
QUICK_RUN = False
BASE_EPOCHS = 8 if QUICK_RUN else 40
LARGE_EPOCHS = 6 if QUICK_RUN else 25

print(f'{len(DATASETS)} jeux sélectionnés:', DATASETS)

14 jeux sélectionnés: ['hyconex/adult', 'hyconex/audit', 'hyconex/blobs', 'hyconex/compas', 'hyconex/german_credit', 'hyconex/heloc', 'hyconex/law', 'hyconex/moons', 'hyconex/moons_with_blob', 'hyconex/wine', 'hyperlogic/brca-n', 'hyperlogic/brca-s', 'hyperlogic/cardio', 'hyperlogic/disease']

In [ ]:
def make_config(splits: TabularDatasetSplits) -> HybridDRConfig:
    n_classes = len(splits.class_names)
    n_feat = splits.X_train.shape[1]
    large = n_feat > 200 or n_classes > 8
    epochs = LARGE_EPOCHS if large else BASE_EPOCHS

    num_rules = 64
    batch = 128
    if n_feat > 500:
        num_rules = 48
        batch = 256
    if n_classes > 20:
        num_rules = min(96, max(48, n_classes * 2))
    if splits.name in ('moons', 'blobs', 'wine', 'law'):
        num_rules = 24
        batch = 32

    return HybridDRConfig(
        seed=SEED,
        epochs=epochs,
        batch_size=batch,
        lr=1e-3,
        num_rules=num_rules,
        bins_per_feature=4,
        hyper_hidden_dim=128,
        tabresnet_n_blocks=4,
        tabresnet_dropout=0.1,
        cf_lambda=0.15,
        flip_lambda=0.06,
        rule_sparsity_lambda=0.002,
        temperature=0.8,
        input_encoding=splits.input_encoding,
    )


def train_on_dataset(key: str) -> dict:
    splits = ALL_LOADERS[key]()
    cfg = make_config(splits)
    trainer = HybridDRTrainer(cfg, device=device)

    print(f"\n{'=' * 72}\n{key} | train {splits.X_train.shape} | classes {len(splits.class_names)} | enc={splits.input_encoding}\n{'=' * 72}")

    result = trainer.fit(
        splits.X_train,
        splits.y_train,
        x_val_cont=splits.X_val,
        y_val=splits.y_val,
        feature_names=splits.feature_names,
        class_names=splits.class_names,
        verbose=True,
    )
    metrics = trainer.evaluate(splits.X_test, splits.y_test, counterfactuals=True)
    rules = trainer.export_rules(top_per_rule=4, min_abs_weight=0.05)

    return {
        'key': key,
        'name': splits.name,
        'splits': splits,
        'trainer': trainer,
        'result': result,
        'metrics': metrics,
        'rules': rules,
    }


def metrics_row(run: dict) -> dict:
    m = run['metrics']
    cf = m.get('counterfactuals', {})
    return {
        'dataset': run['key'],
        'best_val_acc': run['result'].best_val_accuracy,
        'test_acc': m.get('accuracy'),
        'test_auroc': m.get('auroc_ovr'),
        'cf_validity': cf.get('validity_cf'),
        'cf_changed_bits': cf.get('changed_bits_mean'),
        'cf_l1_cont': cf.get('proximity_l1_cont_mean'),
        'n_rules': len(run['rules']),
        'n_binary_features': run['trainer'].binarizer.n_binary_features_,
    }

## Entraînement

In [4]:
runs: dict[str, dict] = {}
failures: dict[str, str] = {}

for ds_key in DATASETS:
    try:
        runs[ds_key] = train_on_dataset(ds_key)
    except FileNotFoundError as exc:
        failures[ds_key] = str(exc)
        print('SKIP', ds_key, '→', exc)
    except Exception as exc:
        failures[ds_key] = str(exc)
        print('ERREUR', ds_key, '→', exc)

if runs:
    summary_df = pd.DataFrame([metrics_row(r) for r in runs.values()])
    display(summary_df.round(4))
else:
    print('Aucun jeu entraîné. Vérifiez HyConEx/data et HyperLogic/data.')

if failures:
    print('\nJeux ignorés:')
    for k, v in failures.items():
        print('-', k, ':', v)

========================================================================
hyconex/adult | train (20838, 34) | classes 2 | enc=bipolar
========================================================================
[Epoch 001/40] loss=0.6204 val_acc=0.8071 val_auroc=0.8739 best(accuracy)=0.8071
[Epoch 002/40] loss=0.5278 val_acc=0.7681 val_auroc=0.8771 best(accuracy)=0.8071
[Epoch 003/40] loss=0.5149 val_acc=0.7449 val_auroc=0.8808 best(accuracy)=0.8071
[Epoch 004/40] loss=0.5050 val_acc=0.7541 val_auroc=0.8802 best(accuracy)=0.8071
[Epoch 005/40] loss=0.4989 val_acc=0.7704 val_auroc=0.8793 best(accuracy)=0.8071
[Epoch 006/40] loss=0.4998 val_acc=0.7729 val_auroc=0.8806 best(accuracy)=0.8071
[Epoch 007/40] loss=0.4947 val_acc=0.8048 val_auroc=0.8805 best(accuracy)=0.8071
[Epoch 008/40] loss=0.4941 val_acc=0.7871 val_auroc=0.8810 best(accuracy)=0.8071
[Epoch 009/40] loss=0.4881 val_acc=0.7678 val_auroc=0.8788 best(accuracy)=0.8071
[Epoch 010/40] loss=0.4878 val_acc=0.7846 val_auroc=0.8803 best(accuracy)=0.8071
[Epoch 011/40] loss=0.4845 val_acc=0.7631 val_auroc=0.8792 best(accuracy)=0.8071
[Epoch 012/40] loss=0.5256 val_acc=0.7797 val_auroc=0.8806 best(accuracy)=0.8071
[Epoch 013/40] loss=0.5204 val_acc=0.7900 val_auroc=0.8748 best(accuracy)=0.8071
[Epoch 014/40] loss=0.5346 val_acc=0.7712 val_auroc=0.8775 best(accuracy)=0.8071
[Epoch 015/40] loss=0.4890 val_acc=0.7516 val_auroc=0.8750 best(accuracy)=0.8071
[Epoch 016/40] loss=0.4814 val_acc=0.7603 val_auroc=0.8781 best(accuracy)=0.8071
[Epoch 017/40] loss=0.4744 val_acc=0.7557 val_auroc=0.8759 best(accuracy)=0.8071
[Epoch 018/40] loss=0.4729 val_acc=0.7718 val_auroc=0.8724 best(accuracy)=0.8071
[Epoch 019/40] loss=0.4700 val_acc=0.7614 val_auroc=0.8753 best(accuracy)=0.8071
[Epoch 020/40] loss=0.4675 val_acc=0.7557 val_auroc=0.8749 best(accuracy)=0.8071
[Epoch 021/40] loss=0.4650 val_acc=0.7649 val_auroc=0.8745 best(accuracy)=0.8071
[Epoch 022/40] loss=0.5039 val_acc=0.7806 val_auroc=0.8713 best(accuracy)=0.8071
[Epoch 023/40] loss=0.4601 val_acc=0.7727 val_auroc=0.8707 best(accuracy)=0.8071
[Epoch 024/40] loss=0.4573 val_acc=0.7841 val_auroc=0.8718 best(accuracy)=0.8071
[Epoch 025/40] loss=0.4571 val_acc=0.7603 val_auroc=0.8729 best(accuracy)=0.8071
[Epoch 026/40] loss=0.4529 val_acc=0.7512 val_auroc=0.8686 best(accuracy)=0.8071
[Epoch 027/40] loss=0.4518 val_acc=0.7946 val_auroc=0.8694 best(accuracy)=0.8071
[Epoch 028/40] loss=0.4514 val_acc=0.7668 val_auroc=0.8713 best(accuracy)=0.8071
[Epoch 029/40] loss=0.4475 val_acc=0.7835 val_auroc=0.8670 best(accuracy)=0.8071
[Epoch 030/40] loss=0.4457 val_acc=0.7699 val_auroc=0.8663 best(accuracy)=0.8071
[Epoch 031/40] loss=0.4457 val_acc=0.7664 val_auroc=0.8655 best(accuracy)=0.8071
[Epoch 032/40] loss=0.4419 val_acc=0.7722 val_auroc=0.8641 best(accuracy)=0.8071
[Epoch 033/40] loss=0.4398 val_acc=0.7660 val_auroc=0.8663 best(accuracy)=0.8071
[Epoch 034/40] loss=0.4381 val_acc=0.7672 val_auroc=0.8649 best(accuracy)=0.8071
[Epoch 035/40] loss=0.4371 val_acc=0.7614 val_auroc=0.8646 best(accuracy)=0.8071
[Epoch 036/40] loss=0.4349 val_acc=0.7585 val_auroc=0.8626 best(accuracy)=0.8071
[Epoch 037/40] loss=0.4365 val_acc=0.7104 val_auroc=0.8614 best(accuracy)=0.8071
[Epoch 038/40] loss=0.4454 val_acc=0.7655 val_auroc=0.8592 best(accuracy)=0.8071
[Epoch 039/40] loss=0.4304 val_acc=0.7432 val_auroc=0.8601 best(accuracy)=0.8071
[Epoch 040/40] loss=0.4273 val_acc=0.7791 val_auroc=0.8632 best(accuracy)=0.8071
  binarizer mode=bipolar | early_stop=accuracy

========================================================================
hyconex/audit | train (390, 23) | classes 2 | enc=quantize
========================================================================
[Epoch 001/40] loss=1.4078 val_acc=0.5000 val_auroc=0.9883 best(accuracy)=0.5000
[Epoch 002/40] loss=0.7367 val_acc=0.8469 val_auroc=0.9913 best(accuracy)=0.8469
[Epoch 003/40] loss=0.5626 val_acc=0.9592 val_auroc=0.9967 best(accuracy)=0.9592
[Epoch 004/40] loss=0.5384 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=0.9898
[Epoch 005/40] loss=0.5132 val_acc=1.0000 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 006/40] loss=0.4991 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 007/40] loss=0.4963 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 008/40] loss=0.4758 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 009/40] loss=0.3858 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 010/40] loss=0.3481 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 011/40] loss=0.3599 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 012/40] loss=0.3886 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 013/40] loss=0.4199 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 014/40] loss=0.4639 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 015/40] loss=0.4588 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 016/40] loss=0.3991 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 017/40] loss=0.3496 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 018/40] loss=0.3294 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 019/40] loss=0.3106 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 020/40] loss=0.2871 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 021/40] loss=0.2461 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 022/40] loss=0.1709 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 023/40] loss=0.1320 val_acc=1.0000 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 024/40] loss=0.0734 val_acc=1.0000 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 025/40] loss=0.0504 val_acc=1.0000 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 026/40] loss=0.0388 val_acc=1.0000 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 027/40] loss=0.0431 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 028/40] loss=0.0360 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 029/40] loss=0.0320 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 030/40] loss=0.0324 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 031/40] loss=0.0330 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 032/40] loss=0.0311 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 033/40] loss=0.0311 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 034/40] loss=0.0311 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 035/40] loss=0.0330 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 036/40] loss=0.0315 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 037/40] loss=0.0309 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 038/40] loss=0.0320 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 039/40] loss=0.0324 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 040/40] loss=0.0329 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
  binarizer mode=quantize | early_stop=accuracy

========================================================================
hyconex/blobs | train (959, 2) | classes 3 | enc=quantize
========================================================================
[Epoch 001/40] loss=0.5981 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9500
[Epoch 002/40] loss=0.3200 val_acc=0.9208 val_auroc=0.9965 best(accuracy)=0.9500
[Epoch 003/40] loss=0.2806 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9500
[Epoch 004/40] loss=0.2503 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 005/40] loss=0.2285 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 006/40] loss=0.2696 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 007/40] loss=0.2262 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 008/40] loss=0.2362 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 009/40] loss=0.2325 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 010/40] loss=0.2186 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 011/40] loss=0.2181 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 012/40] loss=0.2151 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 013/40] loss=0.2132 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 014/40] loss=0.2245 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 015/40] loss=0.2263 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 016/40] loss=0.2321 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 017/40] loss=0.2166 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 018/40] loss=0.2112 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 019/40] loss=0.2184 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 020/40] loss=0.2240 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 021/40] loss=0.2098 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 022/40] loss=0.2073 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 023/40] loss=0.2060 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 024/40] loss=0.2291 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 025/40] loss=0.2104 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 026/40] loss=0.2091 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 027/40] loss=0.2081 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 028/40] loss=0.2075 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 029/40] loss=0.2052 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 030/40] loss=0.2091 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 031/40] loss=0.2091 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 032/40] loss=0.2073 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 033/40] loss=0.2059 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 034/40] loss=0.2078 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 035/40] loss=0.2083 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 036/40] loss=0.2105 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 037/40] loss=0.2075 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 038/40] loss=0.2053 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 039/40] loss=0.2703 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 040/40] loss=0.2160 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
  binarizer mode=quantize | early_stop=accuracy

D:\ecole\master 2\recherche\INN\projet\HyConEx\counterfactuals\datasets\compas.py:43: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  raw_data["length_of_stay"].fillna(
D:\ecole\master 2\recherche\INN\projet\HyConEx\counterfactuals\datasets\compas.py:46: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  raw_data["days_b_screening_arrest"].fillna(

========================================================================
hyconex/compas | train (2693, 25) | classes 3 | enc=bipolar
========================================================================
[Epoch 001/40] loss=1.3345 val_acc=0.5475 val_auroc=0.7311 best(accuracy)=0.5475
[Epoch 002/40] loss=1.1685 val_acc=0.5623 val_auroc=0.7542 best(accuracy)=0.5623
[Epoch 003/40] loss=1.1382 val_acc=0.5564 val_auroc=0.7509 best(accuracy)=0.5623
[Epoch 004/40] loss=1.1114 val_acc=0.5668 val_auroc=0.7520 best(accuracy)=0.5668
[Epoch 005/40] loss=1.1022 val_acc=0.5549 val_auroc=0.7433 best(accuracy)=0.5668
[Epoch 006/40] loss=1.1014 val_acc=0.5682 val_auroc=0.7514 best(accuracy)=0.5682
[Epoch 007/40] loss=1.0710 val_acc=0.5267 val_auroc=0.7460 best(accuracy)=0.5682
[Epoch 008/40] loss=1.0767 val_acc=0.5564 val_auroc=0.7474 best(accuracy)=0.5682
[Epoch 009/40] loss=1.0671 val_acc=0.5623 val_auroc=0.7495 best(accuracy)=0.5682
[Epoch 010/40] loss=1.0541 val_acc=0.5579 val_auroc=0.7477 best(accuracy)=0.5682
[Epoch 011/40] loss=1.0578 val_acc=0.5653 val_auroc=0.7495 best(accuracy)=0.5682
[Epoch 012/40] loss=1.0543 val_acc=0.5386 val_auroc=0.7444 best(accuracy)=0.5682
[Epoch 013/40] loss=1.0478 val_acc=0.5801 val_auroc=0.7479 best(accuracy)=0.5801
[Epoch 014/40] loss=1.0329 val_acc=0.5697 val_auroc=0.7466 best(accuracy)=0.5801
[Epoch 015/40] loss=1.0291 val_acc=0.5608 val_auroc=0.7464 best(accuracy)=0.5801
[Epoch 016/40] loss=1.0255 val_acc=0.5653 val_auroc=0.7421 best(accuracy)=0.5801
[Epoch 017/40] loss=1.0205 val_acc=0.5445 val_auroc=0.7315 best(accuracy)=0.5801
[Epoch 018/40] loss=1.0252 val_acc=0.5534 val_auroc=0.7415 best(accuracy)=0.5801
[Epoch 019/40] loss=1.0097 val_acc=0.5697 val_auroc=0.7420 best(accuracy)=0.5801
[Epoch 020/40] loss=1.0231 val_acc=0.5564 val_auroc=0.7323 best(accuracy)=0.5801
[Epoch 021/40] loss=1.0258 val_acc=0.5430 val_auroc=0.7384 best(accuracy)=0.5801
[Epoch 022/40] loss=1.0142 val_acc=0.5608 val_auroc=0.7392 best(accuracy)=0.5801
[Epoch 023/40] loss=1.0092 val_acc=0.5490 val_auroc=0.7314 best(accuracy)=0.5801
[Epoch 024/40] loss=0.9967 val_acc=0.5593 val_auroc=0.7358 best(accuracy)=0.5801
[Epoch 025/40] loss=0.9884 val_acc=0.5460 val_auroc=0.7376 best(accuracy)=0.5801
[Epoch 026/40] loss=0.9840 val_acc=0.5445 val_auroc=0.7314 best(accuracy)=0.5801
[Epoch 027/40] loss=0.9916 val_acc=0.5608 val_auroc=0.7272 best(accuracy)=0.5801
[Epoch 028/40] loss=0.9827 val_acc=0.5519 val_auroc=0.7348 best(accuracy)=0.5801
[Epoch 029/40] loss=0.9819 val_acc=0.5638 val_auroc=0.7309 best(accuracy)=0.5801
[Epoch 030/40] loss=0.9772 val_acc=0.5401 val_auroc=0.7320 best(accuracy)=0.5801
[Epoch 031/40] loss=0.9756 val_acc=0.5445 val_auroc=0.7306 best(accuracy)=0.5801
[Epoch 032/40] loss=0.9794 val_acc=0.5623 val_auroc=0.7299 best(accuracy)=0.5801
[Epoch 033/40] loss=0.9660 val_acc=0.5297 val_auroc=0.7249 best(accuracy)=0.5801
[Epoch 034/40] loss=0.9648 val_acc=0.5608 val_auroc=0.7238 best(accuracy)=0.5801
[Epoch 035/40] loss=0.9778 val_acc=0.5430 val_auroc=0.7306 best(accuracy)=0.5801
[Epoch 036/40] loss=0.9674 val_acc=0.5445 val_auroc=0.7297 best(accuracy)=0.5801
[Epoch 037/40] loss=0.9573 val_acc=0.5490 val_auroc=0.7242 best(accuracy)=0.5801
[Epoch 038/40] loss=0.9574 val_acc=0.5475 val_auroc=0.7287 best(accuracy)=0.5801
[Epoch 039/40] loss=0.9529 val_acc=0.5119 val_auroc=0.7178 best(accuracy)=0.5801
[Epoch 040/40] loss=0.9526 val_acc=0.5564 val_auroc=0.7319 best(accuracy)=0.5801
  binarizer mode=bipolar | early_stop=accuracy
Index(['default', 'account_check_status', 'duration_in_month',
       'credit_history', 'purpose', 'credit_amount', 'savings',
       'present_emp_since', 'installment_as_income_perc',
       'personal_status_sex', 'other_debtors', 'present_res_since', 'property',
       'age', 'other_installment_plans', 'housing', 'credits_this_bank', 'job',
       'people_under_maintenance', 'telephone', 'foreign_worker'],
      dtype='object')

========================================================================
hyconex/german_credit | train (384, 74) | classes 2 | enc=bipolar
========================================================================
[Epoch 001/40] loss=1.7377 val_acc=0.5000 val_auroc=0.5130 best(accuracy)=0.5000
[Epoch 002/40] loss=0.9568 val_acc=0.5000 val_auroc=0.5616 best(accuracy)=0.5000
[Epoch 003/40] loss=0.8334 val_acc=0.5938 val_auroc=0.6215 best(accuracy)=0.5938
[Epoch 004/40] loss=0.7756 val_acc=0.5208 val_auroc=0.6458 best(accuracy)=0.5938
[Epoch 005/40] loss=0.7416 val_acc=0.6354 val_auroc=0.6628 best(accuracy)=0.6354
[Epoch 006/40] loss=0.7580 val_acc=0.5833 val_auroc=0.6680 best(accuracy)=0.6354
[Epoch 007/40] loss=0.7340 val_acc=0.6458 val_auroc=0.6675 best(accuracy)=0.6458
[Epoch 008/40] loss=0.7787 val_acc=0.5938 val_auroc=0.6736 best(accuracy)=0.6458
[Epoch 009/40] loss=0.7014 val_acc=0.6042 val_auroc=0.6771 best(accuracy)=0.6458
[Epoch 010/40] loss=0.7060 val_acc=0.6042 val_auroc=0.6801 best(accuracy)=0.6458
[Epoch 011/40] loss=0.6672 val_acc=0.6042 val_auroc=0.6871 best(accuracy)=0.6458
[Epoch 012/40] loss=0.6399 val_acc=0.6042 val_auroc=0.6901 best(accuracy)=0.6458
[Epoch 013/40] loss=0.6221 val_acc=0.5729 val_auroc=0.6931 best(accuracy)=0.6458
[Epoch 014/40] loss=0.5939 val_acc=0.6250 val_auroc=0.7036 best(accuracy)=0.6458
[Epoch 015/40] loss=0.5773 val_acc=0.6250 val_auroc=0.6957 best(accuracy)=0.6458
[Epoch 016/40] loss=0.5520 val_acc=0.6146 val_auroc=0.7023 best(accuracy)=0.6458
[Epoch 017/40] loss=0.5278 val_acc=0.6458 val_auroc=0.6810 best(accuracy)=0.6458
[Epoch 018/40] loss=0.5218 val_acc=0.6250 val_auroc=0.6753 best(accuracy)=0.6458
[Epoch 019/40] loss=0.5205 val_acc=0.6354 val_auroc=0.6771 best(accuracy)=0.6458
[Epoch 020/40] loss=0.5206 val_acc=0.6458 val_auroc=0.6814 best(accuracy)=0.6458
[Epoch 021/40] loss=0.5099 val_acc=0.6667 val_auroc=0.6997 best(accuracy)=0.6667
[Epoch 022/40] loss=0.5059 val_acc=0.6250 val_auroc=0.6984 best(accuracy)=0.6667
[Epoch 023/40] loss=0.4909 val_acc=0.6458 val_auroc=0.6879 best(accuracy)=0.6667
[Epoch 024/40] loss=0.5024 val_acc=0.6562 val_auroc=0.6671 best(accuracy)=0.6667
[Epoch 025/40] loss=0.4987 val_acc=0.6562 val_auroc=0.6602 best(accuracy)=0.6667
[Epoch 026/40] loss=0.4985 val_acc=0.6354 val_auroc=0.6610 best(accuracy)=0.6667
[Epoch 027/40] loss=0.4931 val_acc=0.6250 val_auroc=0.6576 best(accuracy)=0.6667
[Epoch 028/40] loss=0.4846 val_acc=0.6354 val_auroc=0.6562 best(accuracy)=0.6667
[Epoch 029/40] loss=0.5026 val_acc=0.6354 val_auroc=0.6610 best(accuracy)=0.6667
[Epoch 030/40] loss=0.4948 val_acc=0.6667 val_auroc=0.6606 best(accuracy)=0.6667
[Epoch 031/40] loss=0.4927 val_acc=0.6458 val_auroc=0.6523 best(accuracy)=0.6667
[Epoch 032/40] loss=0.4967 val_acc=0.6354 val_auroc=0.6463 best(accuracy)=0.6667
[Epoch 033/40] loss=0.4928 val_acc=0.6354 val_auroc=0.6701 best(accuracy)=0.6667
[Epoch 034/40] loss=0.4915 val_acc=0.6354 val_auroc=0.6840 best(accuracy)=0.6667
[Epoch 035/40] loss=0.4905 val_acc=0.6250 val_auroc=0.6853 best(accuracy)=0.6667
[Epoch 036/40] loss=0.4909 val_acc=0.6458 val_auroc=0.6840 best(accuracy)=0.6667
[Epoch 037/40] loss=0.4869 val_acc=0.6354 val_auroc=0.6892 best(accuracy)=0.6667
[Epoch 038/40] loss=0.4845 val_acc=0.6458 val_auroc=0.6931 best(accuracy)=0.6667
[Epoch 039/40] loss=0.4876 val_acc=0.6354 val_auroc=0.6901 best(accuracy)=0.6667
[Epoch 040/40] loss=0.4783 val_acc=0.6354 val_auroc=0.6797 best(accuracy)=0.6667
  binarizer mode=bipolar | early_stop=accuracy

========================================================================
hyconex/heloc | train (6310, 23) | classes 2 | enc=quantize
========================================================================
[Epoch 001/40] loss=0.8373 val_acc=0.6952 val_auroc=0.7927 best(accuracy)=0.6952
[Epoch 002/40] loss=0.7467 val_acc=0.7104 val_auroc=0.7953 best(accuracy)=0.7104
[Epoch 003/40] loss=0.7378 val_acc=0.7237 val_auroc=0.7961 best(accuracy)=0.7237
[Epoch 004/40] loss=0.7273 val_acc=0.7123 val_auroc=0.7889 best(accuracy)=0.7237
[Epoch 005/40] loss=0.7184 val_acc=0.7047 val_auroc=0.7949 best(accuracy)=0.7237
[Epoch 006/40] loss=0.7164 val_acc=0.6869 val_auroc=0.7876 best(accuracy)=0.7237
[Epoch 007/40] loss=0.7131 val_acc=0.7180 val_auroc=0.7901 best(accuracy)=0.7237
[Epoch 008/40] loss=0.6827 val_acc=0.7307 val_auroc=0.7868 best(accuracy)=0.7307
[Epoch 009/40] loss=0.6406 val_acc=0.7085 val_auroc=0.7796 best(accuracy)=0.7307
[Epoch 010/40] loss=0.5847 val_acc=0.6996 val_auroc=0.7781 best(accuracy)=0.7307
[Epoch 011/40] loss=0.5628 val_acc=0.7174 val_auroc=0.7703 best(accuracy)=0.7307
[Epoch 012/40] loss=0.5852 val_acc=0.7066 val_auroc=0.7613 best(accuracy)=0.7307
[Epoch 013/40] loss=0.5197 val_acc=0.7047 val_auroc=0.7594 best(accuracy)=0.7307
[Epoch 014/40] loss=0.4944 val_acc=0.7117 val_auroc=0.7593 best(accuracy)=0.7307
[Epoch 015/40] loss=0.4705 val_acc=0.6933 val_auroc=0.7423 best(accuracy)=0.7307
[Epoch 016/40] loss=0.5047 val_acc=0.6762 val_auroc=0.7518 best(accuracy)=0.7307
[Epoch 017/40] loss=0.4056 val_acc=0.7003 val_auroc=0.7493 best(accuracy)=0.7307
[Epoch 018/40] loss=0.3912 val_acc=0.6958 val_auroc=0.7423 best(accuracy)=0.7307
[Epoch 019/40] loss=0.3730 val_acc=0.6895 val_auroc=0.7470 best(accuracy)=0.7307
[Epoch 020/40] loss=0.3435 val_acc=0.6907 val_auroc=0.7323 best(accuracy)=0.7307
[Epoch 021/40] loss=0.3106 val_acc=0.7015 val_auroc=0.7338 best(accuracy)=0.7307
[Epoch 022/40] loss=0.2994 val_acc=0.6876 val_auroc=0.7288 best(accuracy)=0.7307
[Epoch 023/40] loss=0.2735 val_acc=0.6850 val_auroc=0.7242 best(accuracy)=0.7307
[Epoch 024/40] loss=0.2532 val_acc=0.6819 val_auroc=0.7223 best(accuracy)=0.7307
[Epoch 025/40] loss=0.2515 val_acc=0.6882 val_auroc=0.7311 best(accuracy)=0.7307
[Epoch 026/40] loss=0.2262 val_acc=0.6667 val_auroc=0.7143 best(accuracy)=0.7307
[Epoch 027/40] loss=0.2129 val_acc=0.6965 val_auroc=0.7338 best(accuracy)=0.7307
[Epoch 028/40] loss=0.2174 val_acc=0.6825 val_auroc=0.7298 best(accuracy)=0.7307
[Epoch 029/40] loss=0.2016 val_acc=0.6857 val_auroc=0.7307 best(accuracy)=0.7307
[Epoch 030/40] loss=0.1994 val_acc=0.6762 val_auroc=0.7263 best(accuracy)=0.7307
[Epoch 031/40] loss=0.1847 val_acc=0.6578 val_auroc=0.7103 best(accuracy)=0.7307
[Epoch 032/40] loss=0.1872 val_acc=0.6660 val_auroc=0.7081 best(accuracy)=0.7307
[Epoch 033/40] loss=0.1690 val_acc=0.6711 val_auroc=0.7157 best(accuracy)=0.7307
[Epoch 034/40] loss=0.1556 val_acc=0.6755 val_auroc=0.7150 best(accuracy)=0.7307
[Epoch 035/40] loss=0.2462 val_acc=0.6787 val_auroc=0.7063 best(accuracy)=0.7307
[Epoch 036/40] loss=0.5242 val_acc=0.6971 val_auroc=0.7276 best(accuracy)=0.7307
[Epoch 037/40] loss=0.2558 val_acc=0.6838 val_auroc=0.7204 best(accuracy)=0.7307
[Epoch 038/40] loss=0.1472 val_acc=0.6806 val_auroc=0.7259 best(accuracy)=0.7307
[Epoch 039/40] loss=0.1541 val_acc=0.6863 val_auroc=0.7255 best(accuracy)=0.7307
[Epoch 040/40] loss=0.1531 val_acc=0.6819 val_auroc=0.7302 best(accuracy)=0.7307
  binarizer mode=quantize | early_stop=accuracy

========================================================================
hyconex/law | train (1420, 3) | classes 2 | enc=quantize
========================================================================
[Epoch 001/40] loss=0.7212 val_acc=0.7107 val_auroc=0.7567 best(accuracy)=0.7107
[Epoch 002/40] loss=0.6569 val_acc=0.7107 val_auroc=0.7866 best(accuracy)=0.7107
[Epoch 003/40] loss=0.6356 val_acc=0.6938 val_auroc=0.7870 best(accuracy)=0.7107
[Epoch 004/40] loss=0.6265 val_acc=0.7079 val_auroc=0.7891 best(accuracy)=0.7107
[Epoch 005/40] loss=0.6012 val_acc=0.6938 val_auroc=0.7904 best(accuracy)=0.7107
[Epoch 006/40] loss=0.5840 val_acc=0.7051 val_auroc=0.7837 best(accuracy)=0.7107
[Epoch 007/40] loss=0.6068 val_acc=0.6938 val_auroc=0.7922 best(accuracy)=0.7107
[Epoch 008/40] loss=0.5843 val_acc=0.7135 val_auroc=0.7936 best(accuracy)=0.7135
[Epoch 009/40] loss=0.5917 val_acc=0.7163 val_auroc=0.7908 best(accuracy)=0.7163
[Epoch 010/40] loss=0.5833 val_acc=0.6882 val_auroc=0.7882 best(accuracy)=0.7163
[Epoch 011/40] loss=0.5855 val_acc=0.7135 val_auroc=0.7907 best(accuracy)=0.7163
[Epoch 012/40] loss=0.6063 val_acc=0.7135 val_auroc=0.7886 best(accuracy)=0.7163
[Epoch 013/40] loss=0.5727 val_acc=0.6994 val_auroc=0.7827 best(accuracy)=0.7163
[Epoch 014/40] loss=0.5820 val_acc=0.7022 val_auroc=0.7876 best(accuracy)=0.7163
[Epoch 015/40] loss=0.5910 val_acc=0.7051 val_auroc=0.7841 best(accuracy)=0.7163
[Epoch 016/40] loss=0.5707 val_acc=0.7135 val_auroc=0.7863 best(accuracy)=0.7163
[Epoch 017/40] loss=0.5687 val_acc=0.7107 val_auroc=0.7894 best(accuracy)=0.7163
[Epoch 018/40] loss=0.5745 val_acc=0.7079 val_auroc=0.7884 best(accuracy)=0.7163
[Epoch 019/40] loss=0.5754 val_acc=0.7022 val_auroc=0.7864 best(accuracy)=0.7163
[Epoch 020/40] loss=0.5717 val_acc=0.7079 val_auroc=0.7890 best(accuracy)=0.7163
[Epoch 021/40] loss=0.5684 val_acc=0.7135 val_auroc=0.7895 best(accuracy)=0.7163
[Epoch 022/40] loss=0.5688 val_acc=0.7107 val_auroc=0.7904 best(accuracy)=0.7163
[Epoch 023/40] loss=0.5602 val_acc=0.7079 val_auroc=0.7863 best(accuracy)=0.7163
[Epoch 024/40] loss=0.5735 val_acc=0.7022 val_auroc=0.7877 best(accuracy)=0.7163
[Epoch 025/40] loss=0.5632 val_acc=0.7163 val_auroc=0.7885 best(accuracy)=0.7163
[Epoch 026/40] loss=0.5656 val_acc=0.7135 val_auroc=0.7881 best(accuracy)=0.7163
[Epoch 027/40] loss=0.5610 val_acc=0.7107 val_auroc=0.7877 best(accuracy)=0.7163
[Epoch 028/40] loss=0.5575 val_acc=0.7079 val_auroc=0.7876 best(accuracy)=0.7163
[Epoch 029/40] loss=0.5570 val_acc=0.7107 val_auroc=0.7877 best(accuracy)=0.7163
[Epoch 030/40] loss=0.5566 val_acc=0.7135 val_auroc=0.7864 best(accuracy)=0.7163
[Epoch 031/40] loss=0.5560 val_acc=0.7051 val_auroc=0.7800 best(accuracy)=0.7163
[Epoch 032/40] loss=0.5715 val_acc=0.7051 val_auroc=0.7859 best(accuracy)=0.7163
[Epoch 033/40] loss=0.5596 val_acc=0.7107 val_auroc=0.7842 best(accuracy)=0.7163
[Epoch 034/40] loss=0.5677 val_acc=0.7079 val_auroc=0.7838 best(accuracy)=0.7163
[Epoch 035/40] loss=0.5615 val_acc=0.7051 val_auroc=0.7853 best(accuracy)=0.7163
[Epoch 036/40] loss=0.5601 val_acc=0.7107 val_auroc=0.7875 best(accuracy)=0.7163
[Epoch 037/40] loss=0.5558 val_acc=0.7135 val_auroc=0.7857 best(accuracy)=0.7163
[Epoch 038/40] loss=0.5508 val_acc=0.7135 val_auroc=0.7861 best(accuracy)=0.7163
[Epoch 039/40] loss=0.5603 val_acc=0.7022 val_auroc=0.7879 best(accuracy)=0.7163
[Epoch 040/40] loss=0.5635 val_acc=0.7163 val_auroc=0.7871 best(accuracy)=0.7163
  binarizer mode=quantize | early_stop=accuracy

========================================================================
hyconex/moons | train (654, 2) | classes 2 | enc=quantize
========================================================================
[Epoch 001/40] loss=0.3418 val_acc=0.9573 val_auroc=0.9871 best(accuracy)=0.9573
[Epoch 002/40] loss=0.2169 val_acc=0.9573 val_auroc=0.9899 best(accuracy)=0.9573
[Epoch 003/40] loss=0.1911 val_acc=0.9512 val_auroc=0.9853 best(accuracy)=0.9573
[Epoch 004/40] loss=0.1867 val_acc=0.9573 val_auroc=0.9883 best(accuracy)=0.9573
[Epoch 005/40] loss=0.2093 val_acc=0.9512 val_auroc=0.9860 best(accuracy)=0.9573
[Epoch 006/40] loss=0.1894 val_acc=0.9573 val_auroc=0.9878 best(accuracy)=0.9573
[Epoch 007/40] loss=0.1951 val_acc=0.9573 val_auroc=0.9819 best(accuracy)=0.9573
[Epoch 008/40] loss=0.1892 val_acc=0.9573 val_auroc=0.9817 best(accuracy)=0.9573
[Epoch 009/40] loss=0.2057 val_acc=0.9512 val_auroc=0.9787 best(accuracy)=0.9573
[Epoch 010/40] loss=0.2211 val_acc=0.9512 val_auroc=0.9869 best(accuracy)=0.9573
[Epoch 011/40] loss=0.1582 val_acc=0.9573 val_auroc=0.9900 best(accuracy)=0.9573
[Epoch 012/40] loss=0.1898 val_acc=0.9512 val_auroc=0.9814 best(accuracy)=0.9573
[Epoch 013/40] loss=0.1881 val_acc=0.9573 val_auroc=0.9854 best(accuracy)=0.9573
[Epoch 014/40] loss=0.1765 val_acc=0.9634 val_auroc=0.9874 best(accuracy)=0.9634
[Epoch 015/40] loss=0.1567 val_acc=0.9634 val_auroc=0.9877 best(accuracy)=0.9634
[Epoch 016/40] loss=0.1594 val_acc=0.9512 val_auroc=0.9836 best(accuracy)=0.9634
[Epoch 017/40] loss=0.1583 val_acc=0.9573 val_auroc=0.9875 best(accuracy)=0.9634
[Epoch 018/40] loss=0.1452 val_acc=0.9573 val_auroc=0.9885 best(accuracy)=0.9634
[Epoch 019/40] loss=0.1517 val_acc=0.9634 val_auroc=0.9900 best(accuracy)=0.9634
[Epoch 020/40] loss=0.1556 val_acc=0.9573 val_auroc=0.9869 best(accuracy)=0.9634
[Epoch 021/40] loss=0.1617 val_acc=0.9512 val_auroc=0.9850 best(accuracy)=0.9634
[Epoch 022/40] loss=0.1498 val_acc=0.9512 val_auroc=0.9884 best(accuracy)=0.9634
[Epoch 023/40] loss=0.1473 val_acc=0.9573 val_auroc=0.9859 best(accuracy)=0.9634
[Epoch 024/40] loss=0.1502 val_acc=0.9573 val_auroc=0.9863 best(accuracy)=0.9634
[Epoch 025/40] loss=0.1498 val_acc=0.9573 val_auroc=0.9877 best(accuracy)=0.9634
[Epoch 026/40] loss=0.1449 val_acc=0.9573 val_auroc=0.9850 best(accuracy)=0.9634
[Epoch 027/40] loss=0.1431 val_acc=0.9573 val_auroc=0.9850 best(accuracy)=0.9634
[Epoch 028/40] loss=0.1422 val_acc=0.9573 val_auroc=0.9853 best(accuracy)=0.9634
[Epoch 029/40] loss=0.1599 val_acc=0.9573 val_auroc=0.9850 best(accuracy)=0.9634
[Epoch 030/40] loss=0.1605 val_acc=0.9573 val_auroc=0.9883 best(accuracy)=0.9634
[Epoch 031/40] loss=0.1602 val_acc=0.9573 val_auroc=0.9859 best(accuracy)=0.9634
[Epoch 032/40] loss=0.1522 val_acc=0.9573 val_auroc=0.9868 best(accuracy)=0.9634
[Epoch 033/40] loss=0.1454 val_acc=0.9573 val_auroc=0.9899 best(accuracy)=0.9634
[Epoch 034/40] loss=0.1622 val_acc=0.9573 val_auroc=0.9899 best(accuracy)=0.9634
[Epoch 035/40] loss=0.1442 val_acc=0.9512 val_auroc=0.9884 best(accuracy)=0.9634
[Epoch 036/40] loss=0.1449 val_acc=0.9573 val_auroc=0.9860 best(accuracy)=0.9634
[Epoch 037/40] loss=0.1456 val_acc=0.9512 val_auroc=0.9859 best(accuracy)=0.9634
[Epoch 038/40] loss=0.1451 val_acc=0.9512 val_auroc=0.9859 best(accuracy)=0.9634
[Epoch 039/40] loss=0.1451 val_acc=0.9512 val_auroc=0.9884 best(accuracy)=0.9634
[Epoch 040/40] loss=0.1470 val_acc=0.9573 val_auroc=0.9884 best(accuracy)=0.9634
  binarizer mode=quantize | early_stop=accuracy

========================================================================
hyconex/moons_with_blob | train (639, 2) | classes 2 | enc=quantize
========================================================================
[Epoch 001/40] loss=0.6246 val_acc=0.8562 val_auroc=0.9541 best(accuracy)=0.8562
[Epoch 002/40] loss=0.4468 val_acc=0.8938 val_auroc=0.9630 best(accuracy)=0.8938
[Epoch 003/40] loss=0.3949 val_acc=0.8812 val_auroc=0.9509 best(accuracy)=0.8938
[Epoch 004/40] loss=0.3497 val_acc=0.8938 val_auroc=0.9648 best(accuracy)=0.8938
[Epoch 005/40] loss=0.3551 val_acc=0.8938 val_auroc=0.9648 best(accuracy)=0.8938
[Epoch 006/40] loss=0.3270 val_acc=0.8938 val_auroc=0.9648 best(accuracy)=0.8938
[Epoch 007/40] loss=0.3361 val_acc=0.8812 val_auroc=0.9664 best(accuracy)=0.8938
[Epoch 008/40] loss=0.3256 val_acc=0.8750 val_auroc=0.9591 best(accuracy)=0.8938
[Epoch 009/40] loss=0.3216 val_acc=0.8812 val_auroc=0.9648 best(accuracy)=0.8938
[Epoch 010/40] loss=0.3227 val_acc=0.8938 val_auroc=0.9648 best(accuracy)=0.8938
[Epoch 011/40] loss=0.3161 val_acc=0.8812 val_auroc=0.9653 best(accuracy)=0.8938
[Epoch 012/40] loss=0.3300 val_acc=0.8812 val_auroc=0.9648 best(accuracy)=0.8938
[Epoch 013/40] loss=0.3270 val_acc=0.8812 val_auroc=0.9592 best(accuracy)=0.8938
[Epoch 014/40] loss=0.3154 val_acc=0.8812 val_auroc=0.9648 best(accuracy)=0.8938
[Epoch 015/40] loss=0.3261 val_acc=0.8875 val_auroc=0.9630 best(accuracy)=0.8938
[Epoch 016/40] loss=0.3153 val_acc=0.8812 val_auroc=0.9648 best(accuracy)=0.8938
[Epoch 017/40] loss=0.3074 val_acc=0.8812 val_auroc=0.9592 best(accuracy)=0.8938
[Epoch 018/40] loss=0.3153 val_acc=0.8938 val_auroc=0.9597 best(accuracy)=0.8938
[Epoch 019/40] loss=0.3115 val_acc=0.8938 val_auroc=0.9648 best(accuracy)=0.8938
[Epoch 020/40] loss=0.3168 val_acc=0.8938 val_auroc=0.9653 best(accuracy)=0.8938
[Epoch 021/40] loss=0.3290 val_acc=0.8938 val_auroc=0.9648 best(accuracy)=0.8938
[Epoch 022/40] loss=0.4172 val_acc=0.8812 val_auroc=0.9606 best(accuracy)=0.8938
[Epoch 023/40] loss=0.4128 val_acc=0.8812 val_auroc=0.9606 best(accuracy)=0.8938

,dataset,best_val_acc,test_acc,test_auroc,cf_validity,cf_changed_bits,cf_l1_cont,n_rules,n_binary_features
0,hyconex/adult,0.8071,0.8061,0.8735,0.7593,13.2435,13.2435,64,34
1,hyconex/audit,1.0000,1.0000,1.0000,0.0000,26.4918,2.1854,64,50
2,hyconex/blobs,0.9708,0.9433,0.9974,0.4717,3.9600,0.6322,24,8
3,hyconex/compas,0.5801,0.5083,0.7127,0.4157,11.4893,11.4893,64,25
4,hyconex/german_credit,0.6667,0.6417,0.7200,0.3583,40.3833,39.6333,64,74
5,hyconex/heloc,0.7307,0.7197,0.7846,0.3011,37.2484,5.0663,64,78
6,hyconex/law,0.7163,0.7770,0.8533,0.7995,5.0000,0.7570,24,12
7,hyconex/moons,0.9634,0.9805,0.9885,0.9805,4.4537,0.6892,24,8
8,hyconex/moons_with_blob,0.8938,0.8800,0.9662,0.7800,2.9200,0.6721,64,8
9,hyperlogic/brca-n,0.5000,0.4889,0.5000,0.5111,67.9778,0.0000,64,120
10,hyperlogic/brca-s,0.2667,0.2632,0.5000,0.2456,50.0000,0.0000,64,120
11,hyperlogic/cardio,0.7270,0.7199,0.7899,0.7191,18.2111,18.2111,62,32
12,hyperlogic/disease,1.0000,1.0000,1.0000,0.0000,64.0584,62.7894,82,131

Jeux ignorés:
- hyconex/wine : list index out of range

## Helpers contrefactuels et règles

In [5]:
def flipped_literals(x_orig: np.ndarray, x_cf: np.ndarray, bin_names: list[str], max_show: int = 8) -> list[str]:
    diff = np.where(np.abs(x_orig - x_cf) > 1e-6)[0]
    out = []
    for j in diff[:max_show]:
        out.append(f"{bin_names[j]}: {int(x_orig[j])} → {int(x_cf[j])}")
    if len(diff) > max_show:
        out.append(f"… +{len(diff) - max_show} autres flips")
    return out


def build_cf_table(run: dict, n_examples: int = 5, seed: int = 42) -> pd.DataFrame:
    trainer = run['trainer']
    splits = run['splits']
    model = trainer.model
    assert model is not None

    x_test_bin = trainer.binarizer.transform(splits.X_test)
    x_test_t = torch.tensor(x_test_bin, dtype=torch.float32, device=trainer.device)
    with torch.no_grad():
        logits = model.predict_logits(x_test_t)
        y_pred = torch.argmax(logits, dim=1).cpu().numpy()

    pool = np.where(y_pred == splits.y_test)[0]
    rng = np.random.default_rng(seed)
    n = min(n_examples, len(pool))
    idx = rng.choice(pool, size=n, replace=False) if n > 0 else np.array([], dtype=int)

    if idx.size == 0:
        return pd.DataFrame(columns=['sample', 'true', 'pred', 'target', 'valid_cf', 'n_flips', 'flips'])

    x_sub = torch.tensor(x_test_bin[idx], dtype=torch.float32, device=trainer.device)
    y_pred_orig = torch.tensor(y_pred[idx], dtype=torch.long, device=trainer.device)

    with torch.no_grad():
        x_cf_all, logits_cf_all = model.generate_counterfactuals_all_classes(x_sub, y_pred_orig)
        y_pred_cf = torch.argmax(logits_cf_all, dim=2).cpu().numpy()

    x_sub_np = x_sub.cpu().numpy()
    x_cf_np = x_cf_all.cpu().numpy()
    bin_names = trainer.binarizer.binary_feature_names()
    class_names = splits.class_names

    rows = []
    for i, sample_idx in enumerate(idx):
        src = int(y_pred_orig[i].item())
        for target in range(len(class_names)):
            if target == src:
                continue
            x_cf = x_cf_np[i, target]
            rows.append({
                'sample': int(sample_idx),
                'true': class_names[int(splits.y_test[sample_idx])],
                'pred': class_names[src],
                'target': class_names[target],
                'valid_cf': int(y_pred_cf[i, target] == target),
                'n_flips': int(np.sum(np.abs(x_sub_np[i] - x_cf) > 1e-6)),
                'flips': '; '.join(flipped_literals(x_sub_np[i], x_cf, bin_names)),
            })
    return pd.DataFrame(rows)


def rules_dataframe(run: dict, top_n: int = 10) -> pd.DataFrame:
    rules = run['rules'][:top_n]
    df = pd.DataFrame(rules)
    if 'if' in df.columns:
        df['if'] = df['if'].apply(lambda conds: ' AND\n'.join(conds) if isinstance(conds, list) else conds)
    return df

## Par jeu : contrefactuels et règles

In [6]:
for ds_key, run in runs.items():
    display(Markdown(f"### `{ds_key}` — contrefactuels"))
    cf_df = build_cf_table(run, n_examples=3)
    with pd.option_context('display.max_colwidth', 120, 'display.max_rows', 30):
        display(cf_df)

    display(Markdown(f"### `{ds_key}` — règles HyperLogic (top 10)"))
    rdf = rules_dataframe(run, top_n=10)
    with pd.option_context('display.max_colwidth', None, 'display.max_rows', None, 'display.width', None):
        display(rdf)

### `hyconex/adult` — contrefactuels

,sample,true,pred,target,valid_cf,n_flips,flips
0,4257,0,0,1,1,15,"age_bin0_[0.000,0.151): 1 → -1; age_bin2_[0.274,0.411): -1 → 1; age_bin3_[0.411,1.000): -1 → 1; hours_per_week_bin2_..."
1,600,0,0,1,1,17,"age_bin0_[0.000,0.151): 1 → -1; age_bin2_[0.274,0.411): -1 → 1; age_bin3_[0.411,1.000): -1 → 1; hours_per_week_bin0_..."
2,5045,0,0,1,1,11,"age_bin0_[0.000,0.151): 1 → -1; age_bin2_[0.274,0.411): -1 → 1; age_bin3_[0.411,1.000): -1 → 1; hours_per_week_bin2_..."

### `hyconex/adult` — règles HyperLogic (top 10)

,rule_id,if,then_class,score
0,41,marital_status=Single=+1 AND\neducation=Prof-school=-1 AND\nmarital_status=Married=-1 AND\neducation=HS-grad=-1,0,1.000000
1,36,"occupation=Blue-Collar=-1 AND\nmarital_status=Separated=+1 AND\nage_bin3_[0.411,1.000)=-1 AND\ngender=Female=+1",0,0.997995
2,26,"race=White=+1 AND\nage_bin1_[0.151,0.274)=+1 AND\nworkclass=Self-Employed=-1 AND\nworkclass=Private=-1",1,0.997547
3,4,"age_bin2_[0.274,0.411)=-1 AND\nage_bin0_[0.000,0.151)=-1 AND\neducation=Doctorate=+1 AND\ngender=Male=-1",0,0.995923
4,5,"age_bin3_[0.411,1.000)=+1 AND\nage_bin0_[0.000,0.151)=-1 AND\nrace=White=+1 AND\nworkclass=Government=-1",1,0.994946
5,1,"gender=Male=-1 AND\neducation=School=-1 AND\nage_bin1_[0.151,0.274)=-1 AND\neducation=Prof-school=-1",0,0.991078
6,16,education=Masters=-1 AND\neducation=HS-grad=-1 AND\noccupation=Sales=-1 AND\neducation=Bachelors=-1,1,0.989506
7,32,"race=White=+1 AND\nhours_per_week_bin0_[0.000,0.398)=+1 AND\nworkclass=Government=-1 AND\ngender=Male=-1",0,0.984735
8,25,race=White=+1 AND\nworkclass=Self-Employed=-1 AND\neducation=Masters=-1 AND\nmarital_status=Separated=-1,1,0.978475
9,61,"occupation=Sales=-1 AND\nage_bin3_[0.411,1.000)=+1 AND\nhours_per_week_bin1_[0.398,0.449)=-1 AND\neducation=Doctorate=-1",0,0.974959

### `hyconex/audit` — contrefactuels

,sample,true,pred,target,valid_cf,n_flips,flips
0,79,0,0,1,0,28,"PARA_A_bin0_[0.000,0.004): -1 → 1; PARA_A_bin1_[0.004,0.013): 1 → -1; PARA_A_bin3_[0.038,1.000): -1 → 1; Score_A_bin..."
1,10,0,0,1,0,26,"PARA_A_bin3_[0.038,1.000): -1 → 1; Score_A_bin0_[0.000,0.500): 1 → -1; Score_A_bin1_[0.500,1.000): -1 → 1; PARA_B_bi..."
2,93,0,0,1,0,19,"PARA_A_bin0_[0.000,0.004): -1 → 1; PARA_A_bin3_[0.038,1.000): -1 → 1; Score_A_bin1_[0.500,1.000): 1 → -1; Risk_A_bin..."

### `hyconex/audit` — règles HyperLogic (top 10)

,rule_id,if,then_class,score
0,20,"PARA_B_bin1_[0.004,0.047)=-1 AND\nInherent_Risk_bin1_[0.000,0.003)=+1 AND\nScore_B_bin0_[0.000,1.000)=+1 AND\nInherent_Risk_bin0_[0.000,0.000)=-1",0,0.992966
1,51,"CONTROL_RISK_bin0_[0.000,0.056)=+1 AND\nScore_bin2_[0.500,1.000)=-1 AND\nRisk_A_bin0_[0.000,0.001)=-1 AND\nRisk_B_bin1_[0.001,0.040)=-1",0,0.973531
2,14,"Audit_Risk_bin0_[0.000,0.000)=+1 AND\nScore_A_bin1_[0.500,1.000)=+1 AND\nTOTAL_bin2_[0.011,0.078)=-1 AND\nTOTAL_bin3_[0.078,1.000)=-1",0,0.968318
3,27,"Score_bin1_[0.125,0.500)=+1 AND\nCONTROL_RISK_bin0_[0.000,0.056)=+1 AND\nPARA_A_bin0_[0.000,0.004)=+1 AND\nRisk_C_bin0_[0.000,1.000)=+1",0,0.966190
4,56,"Money_Value_bin0_[0.000,0.000)=-1 AND\nTOTAL_bin1_[0.005,0.011)=-1 AND\nInherent_Risk_bin2_[0.003,0.032)=-1 AND\nCONTROL_RISK_bin1_[0.056,1.000)=-1",1,0.956233
5,38,"PARA_B_bin2_[0.047,1.000)=-1 AND\nRisk_A_bin1_[0.001,0.009)=+1 AND\nPARA_A_bin1_[0.004,0.013)=+1 AND\nRisk_D_bin2_[0.011,1.000)=+1",0,0.948888
6,23,"PARA_A_bin3_[0.038,1.000)=-1 AND\nAudit_Risk_bin1_[0.000,0.005)=-1 AND\nScore_A_bin0_[0.000,0.500)=+1 AND\nPARA_A_bin0_[0.000,0.004)=-1",1,0.932239
7,28,"PARA_B_bin2_[0.047,1.000)=-1 AND\nRisk_D_bin0_[0.000,0.000)=+1 AND\nMoney_Value_bin1_[0.000,0.011)=+1 AND\nRisk_B_bin0_[0.000,0.001)=-1",1,0.921587
8,34,"Inherent_Risk_bin1_[0.000,0.003)=-1 AND\nScore_MV_bin0_[0.000,1.000)=+1 AND\nInherent_Risk_bin3_[0.032,1.000)=+1 AND\nRisk_B_bin2_[0.040,1.000)=-1",0,0.912801
9,43,"Risk_D_bin0_[0.000,0.000)=-1 AND\nDistrict_Loss_bin0_[0.000,1.000)=-1 AND\nPARA_A_bin3_[0.038,1.000)=+1 AND\nPARA_B_bin2_[0.047,1.000)=-1",1,0.911980

### `hyconex/blobs` — contrefactuels

,sample,true,pred,target,valid_cf,n_flips,flips
0,197,1,1,0,1,4,"f0_bin0_[0.000,0.268): -1 → 1; f1_bin1_[0.178,0.491): -1 → 1; f1_bin2_[0.491,0.728): 1 → -1; f1_bin3_[0.728,1.000): ..."
1,197,1,1,2,0,4,"f0_bin0_[0.000,0.268): -1 → 1; f1_bin1_[0.178,0.491): -1 → 1; f1_bin2_[0.491,0.728): 1 → -1; f1_bin3_[0.728,1.000): ..."
2,26,0,0,1,1,4,"f0_bin0_[0.000,0.268): -1 → 1; f0_bin2_[0.442,0.754): 1 → -1; f0_bin3_[0.754,1.000): -1 → 1; f1_bin1_[0.178,0.491): ..."
3,26,0,0,2,0,4,"f0_bin0_[0.000,0.268): -1 → 1; f0_bin2_[0.442,0.754): 1 → -1; f0_bin3_[0.754,1.000): -1 → 1; f1_bin1_[0.178,0.491): ..."
4,232,1,1,0,1,4,"f0_bin0_[0.000,0.268): -1 → 1; f1_bin1_[0.178,0.491): -1 → 1; f1_bin2_[0.491,0.728): 1 → -1; f1_bin3_[0.728,1.000): ..."
5,232,1,1,2,0,4,"f0_bin0_[0.000,0.268): -1 → 1; f1_bin1_[0.178,0.491): -1 → 1; f1_bin2_[0.491,0.728): 1 → -1; f1_bin3_[0.728,1.000): ..."

### `hyconex/blobs` — règles HyperLogic (top 10)

,rule_id,if,then_class,score
0,21,"f0_bin1_[0.268,0.442)=+1 AND\nf1_bin0_[0.000,0.178)=-1 AND\nf1_bin1_[0.178,0.491)=-1 AND\nf0_bin3_[0.754,1.000)=-1",0,0.999995
1,18,"f1_bin1_[0.178,0.491)=+1 AND\nf0_bin2_[0.442,0.754)=+1 AND\nf1_bin2_[0.491,0.728)=-1 AND\nf1_bin0_[0.000,0.178)=-1",1,0.999974
2,8,"f1_bin1_[0.178,0.491)=-1 AND\nf1_bin0_[0.000,0.178)=+1 AND\nf0_bin2_[0.442,0.754)=-1 AND\nf1_bin2_[0.491,0.728)=-1",2,0.999972
3,2,"f1_bin1_[0.178,0.491)=-1 AND\nf0_bin2_[0.442,0.754)=-1 AND\nf1_bin0_[0.000,0.178)=-1 AND\nf0_bin1_[0.268,0.442)=+1",0,0.999931
4,13,"f0_bin2_[0.442,0.754)=+1 AND\nf1_bin1_[0.178,0.491)=-1 AND\nf1_bin0_[0.000,0.178)=-1 AND\nf0_bin1_[0.268,0.442)=-1",0,0.999855
5,7,"f0_bin3_[0.754,1.000)=+1 AND\nf0_bin1_[0.268,0.442)=-1 AND\nf0_bin0_[0.000,0.268)=-1 AND\nf0_bin2_[0.442,0.754)=-1",1,0.999813
6,3,"f1_bin2_[0.491,0.728)=-1 AND\nf0_bin1_[0.268,0.442)=-1 AND\nf0_bin2_[0.442,0.754)=-1 AND\nf0_bin0_[0.000,0.268)=-1",1,0.999581
7,11,"f0_bin3_[0.754,1.000)=+1 AND\nf0_bin0_[0.000,0.268)=-1 AND\nf1_bin0_[0.000,0.178)=-1 AND\nf1_bin1_[0.178,0.491)=-1",1,0.998324
8,19,"f1_bin3_[0.728,1.000)=+1 AND\nf1_bin0_[0.000,0.178)=-1 AND\nf0_bin0_[0.000,0.268)=-1 AND\nf0_bin3_[0.754,1.000)=-1",0,0.991983
9,23,"f0_bin2_[0.442,0.754)=-1 AND\nf1_bin3_[0.728,1.000)=+1 AND\nf1_bin1_[0.178,0.491)=-1 AND\nf0_bin3_[0.754,1.000)=-1",0,0.957222

### `hyconex/compas` — contrefactuels

,sample,true,pred,target,valid_cf,n_flips,flips
0,555,0,0,1,1,12,"age_bin0_[0.000,0.097): -1 → 1; age_bin1_[0.097,0.194): -1 → 1; days_b_screening_arrest_bin1_[0.001,1.000): 1 → -1; ..."
1,555,0,0,2,0,12,"age_bin0_[0.000,0.097): -1 → 1; age_bin1_[0.097,0.194): -1 → 1; days_b_screening_arrest_bin1_[0.001,1.000): 1 → -1; ..."
2,69,0,0,1,1,10,"age_bin0_[0.000,0.097): -1 → 1; age_bin1_[0.097,0.194): -1 → 1; priors_count_bin0_[0.000,0.053): 1 → -1; priors_coun..."
3,69,0,0,2,0,10,"age_bin0_[0.000,0.097): -1 → 1; age_bin1_[0.097,0.194): -1 → 1; priors_count_bin0_[0.000,0.053): 1 → -1; priors_coun..."
4,658,1,1,0,1,12,"age_bin0_[0.000,0.097): -1 → 1; age_bin1_[0.097,0.194): -1 → 1; priors_count_bin1_[0.053,0.158): -1 → 1; priors_coun..."
5,658,1,1,2,0,12,"age_bin0_[0.000,0.097): -1 → 1; age_bin1_[0.097,0.194): -1 → 1; priors_count_bin1_[0.053,0.158): -1 → 1; priors_coun..."

### `hyconex/compas` — règles HyperLogic (top 10)

,rule_id,if,then_class,score
0,53,"c_charge_degree=M=+1 AND\npriors_count_bin0_[0.000,0.053)=+1 AND\ndays_b_screening_arrest_bin0_[0.000,0.001)=-1 AND\nlength_of_stay_bin1_[0.001,0.016)=-1",0,0.991018
1,46,"race=African-American=+1 AND\nage_bin2_[0.194,0.339)=-1 AND\nlength_of_stay_bin2_[0.016,1.000)=-1 AND\nsex=Male=+1",1,0.990974
2,52,"age_bin1_[0.097,0.194)=+1 AND\nage_bin2_[0.194,0.339)=+1 AND\nrace=Other=-1 AND\ntwo_year_recid_bin0_[0.000,1.000)=-1",2,0.989229
3,39,"sex=Male=-1 AND\ntwo_year_recid_bin0_[0.000,1.000)=+1 AND\nage_bin3_[0.339,1.000)=+1 AND\npriors_count_bin0_[0.000,0.053)=+1",0,0.980008
4,62,"race=Native American=+1 AND\nrace=African-American=+1 AND\ndays_b_screening_arrest_bin1_[0.001,1.000)=+1 AND\nis_violent_recid_bin0_[0.000,1.000)=+1",2,0.967539
5,12,"length_of_stay_bin2_[0.016,1.000)=+1 AND\nlength_of_stay_bin1_[0.001,0.016)=+1 AND\npriors_count_bin2_[0.158,1.000)=-1 AND\nage_bin0_[0.000,0.097)=+1",0,0.960907
6,20,"age_bin1_[0.097,0.194)=+1 AND\nrace=Caucasian=+1 AND\nsex=Female=-1 AND\nc_charge_degree=M=+1",0,0.929357
7,18,"sex=Male=-1 AND\nrace=Caucasian=-1 AND\nrace=African-American=-1 AND\npriors_count_bin0_[0.000,0.053)=+1",1,0.925555
8,9,"priors_count_bin2_[0.158,1.000)=+1 AND\npriors_count_bin0_[0.000,0.053)=+1 AND\nc_charge_degree=M=-1 AND\nis_violent_recid_bin0_[0.000,1.000)=-1",2,0.918687
9,40,"length_of_stay_bin1_[0.001,0.016)=-1 AND\nrace=Other=+1 AND\nlength_of_stay_bin0_[0.000,0.001)=+1 AND\npriors_count_bin2_[0.158,1.000)=-1",2,0.916723

### `hyconex/german_credit` — contrefactuels

,sample,true,pred,target,valid_cf,n_flips,flips
0,77,1,1,0,0,47,"duration_in_month_bin0_[0.000,0.118): -1 → 1; duration_in_month_bin1_[0.118,0.250): -1 → 1; duration_in_month_bin3_[..."
1,10,0,0,1,0,42,"duration_in_month_bin0_[0.000,0.118): 1 → -1; duration_in_month_bin2_[0.250,0.382): -1 → 1; duration_in_month_bin3_[..."
2,89,1,1,0,0,38,"duration_in_month_bin1_[0.118,0.250): -1 → 1; duration_in_month_bin2_[0.250,0.382): -1 → 1; credit_amount_bin2_[0.13..."

### `hyconex/german_credit` — règles HyperLogic (top 10)

,rule_id,if,then_class,score
0,1,"property=unknown / no property=+1 AND\npresent_emp_since=... < 1 year =+1 AND\ninstallment_as_income_perc_bin0_[0.000,0.333)=-1 AND\ncredit_history=no credits taken/ all credits paid back duly=+1",1,0.977960
1,29,personal_status_sex=male : single=+1 AND\nother_debtors=co-applicant=+1 AND\nhousing=for free=+1 AND\npersonal_status_sex=female : divorced/separated/married=+1,0,0.955123
2,23,"present_res_since_bin2_[0.667,1.000)=+1 AND\nother_installment_plans=stores=-1 AND\ncredit_history=existing credits paid back duly till now=-1 AND\ninstallment_as_income_perc_bin2_[0.667,1.000)=+1",0,0.950573
3,50,purpose=business=-1 AND\naccount_check_status=>= 200 DM / salary assignments for at least 1 year=+1 AND\naccount_check_status=0 <= ... < 200 DM=-1 AND\naccount_check_status=no checking account=+1,0,0.937337
4,58,account_check_status=< 0 DM=-1 AND\nhousing=for free=+1 AND\nother_installment_plans=none=+1 AND\nsavings=.. >= 1000 DM =-1,1,0.933365
5,8,other_debtors=none=+1 AND\naccount_check_status=< 0 DM=+1 AND\npresent_emp_since=... < 1 year =+1 AND\npurpose=education=-1,1,0.932080
6,51,"other_debtors=co-applicant=-1 AND\ncredit_amount_bin3_[0.285,1.000)=-1 AND\nother_debtors=none=-1 AND\nduration_in_month_bin1_[0.118,0.250)=+1",0,0.917852
7,37,"credit_history=all credits at this bank paid back duly=+1 AND\npresent_emp_since=1 <= ... < 4 years=+1 AND\nsavings=.. >= 1000 DM =-1 AND\nduration_in_month_bin0_[0.000,0.118)=+1",0,0.912836
8,52,"credit_amount_bin0_[0.000,0.067)=-1 AND\naccount_check_status=no checking account=-1 AND\ncredit_history=critical account/ other credits existing (not at this bank)=+1 AND\npersonal_status_sex=male : divorced/separated=+1",0,0.891586
9,17,"present_res_since_bin0_[0.000,0.333)=-1 AND\ncredit_amount_bin0_[0.000,0.067)=+1 AND\nforeign_worker=no=-1 AND\nother_installment_plans=stores=+1",0,0.888017

### `hyconex/heloc` — contrefactuels

,sample,true,pred,target,valid_cf,n_flips,flips
0,1268,Bad,Bad,Good,0,41,"ExternalRiskEstimate_bin0_[0.000,0.508): 1 → -1; MSinceOldestTradeOpen_bin1_[0.169,0.236): 1 → -1; MSinceOldestTrade..."
1,170,Good,Good,Bad,0,41,"ExternalRiskEstimate_bin3_[0.770,1.000): 1 → -1; MSinceOldestTradeOpen_bin1_[0.169,0.236): 1 → -1; MSinceOldestTrade..."
2,1514,Bad,Bad,Good,1,39,"ExternalRiskEstimate_bin0_[0.000,0.508): 1 → -1; MSinceOldestTradeOpen_bin0_[0.000,0.169): 1 → -1; MSinceOldestTrade..."

### `hyconex/heloc` — règles HyperLogic (top 10)

,rule_id,if,then_class,score
0,47,"NumBank2NatlTradesWHighUtilization_bin1_[0.348,0.391)=-1 AND\nAverageMInFile_bin0_[0.000,0.164)=-1 AND\nPercentTradesNeverDelq_bin2_[0.970,1.000)=-1 AND\nNumRevolvingTradesWBalance_bin2_[0.314,0.371)=+1",Bad,1.000000
1,38,"AverageMInFile_bin1_[0.164,0.226)=+1 AND\nNumRevolvingTradesWBalance_bin2_[0.314,0.371)=-1 AND\nPercentTradesNeverDelq_bin1_[0.890,0.970)=+1 AND\nNumTotalTrades_bin1_[0.125,0.202)=-1",Bad,0.999988
2,22,"NumInqLast6Mexcl7days_bin0_[0.000,0.015)=+1 AND\nMaxDelq2PublicRecLast12M_bin1_[0.556,0.667)=+1 AND\nExternalRiskEstimate_bin3_[0.770,1.000)=+1 AND\nMSinceOldestTradeOpen_bin1_[0.169,0.236)=+1",Bad,0.999804
3,11,"ExternalRiskEstimate_bin1_[0.508,0.639)=-1 AND\nNumInqLast6Mexcl7days_bin2_[0.030,1.000)=-1 AND\nMSinceMostRecentTradeOpen_bin2_[0.026,0.053)=-1 AND\nMaxDelqEver_bin1_[0.667,1.000)=-1",Bad,0.997813
4,34,"NumRevolvingTradesWBalance_bin0_[0.000,0.286)=-1 AND\nNumSatisfactoryTrades_bin2_[0.253,0.354)=-1 AND\nNumTradesOpeninLast12M_bin1_[0.053,0.158)=-1 AND\nMSinceOldestTradeOpen_bin3_[0.326,1.000)=-1",Good,0.995628
5,33,"NumInqLast6Mexcl7days_bin2_[0.030,1.000)=-1 AND\nNumInqLast6Mexcl7days_bin0_[0.000,0.015)=+1 AND\nMSinceMostRecentTradeOpen_bin1_[0.013,0.026)=-1 AND\nAverageMInFile_bin2_[0.226,0.289)=+1",Bad,0.995421
6,5,"MSinceMostRecentInqexcl7days_bin1_[0.250,0.281)=+1 AND\nPercentTradesNeverDelq_bin2_[0.970,1.000)=+1 AND\nNumTradesOpeninLast12M_bin1_[0.053,0.158)=-1 AND\nMSinceOldestTradeOpen_bin0_[0.000,0.169)=+1",Bad,0.993994
7,9,"NumInqLast6M_bin1_[0.015,0.030)=-1 AND\nMaxDelq2PublicRecLast12M_bin3_[0.778,1.000)=-1 AND\nAverageMInFile_bin3_[0.289,1.000)=+1 AND\nNumInqLast6M_bin2_[0.030,1.000)=+1",Bad,0.983316
8,55,"MSinceMostRecentInqexcl7days_bin1_[0.250,0.281)=-1 AND\nNumSatisfactoryTrades_bin2_[0.253,0.354)=-1 AND\nNetFractionInstallBurden_bin2_[0.184,1.000)=+1 AND\nNumTradesOpeninLast12M_bin2_[0.158,1.000)=+1",Good,0.977773
9,61,"NumRevolvingTradesWBalance_bin0_[0.000,0.286)=-1 AND\nMSinceMostRecentDelq_bin3_[0.253,1.000)=+1 AND\nExternalRiskEstimate_bin1_[0.508,0.639)=-1 AND\nMSinceMostRecentInqexcl7days_bin2_[0.281,1.000)=+1",Good,0.966674

### `hyconex/law` — contrefactuels

,sample,true,pred,target,valid_cf,n_flips,flips
0,288,1,1,0,1,5,"lsat_bin2_[0.612,0.731): -1 → 1; lsat_bin3_[0.731,1.000): 1 → -1; gpa_bin1_[0.476,0.619): 1 → -1; zfygpa_bin1_[0.376..."
1,35,0,0,1,1,5,"lsat_bin1_[0.463,0.612): 1 → -1; lsat_bin2_[0.612,0.731): -1 → 1; gpa_bin1_[0.476,0.619): 1 → -1; zfygpa_bin2_[0.484..."
2,342,0,0,1,1,5,"lsat_bin0_[0.000,0.463): 1 → -1; lsat_bin2_[0.612,0.731): -1 → 1; gpa_bin2_[0.619,0.762): 1 → -1; zfygpa_bin2_[0.484..."

### `hyconex/law` — règles HyperLogic (top 10)

,rule_id,if,then_class,score
0,3,"lsat_bin2_[0.612,0.731)=+1 AND\ngpa_bin2_[0.619,0.762)=+1 AND\nzfygpa_bin3_[0.607,1.000)=+1 AND\nlsat_bin0_[0.000,0.463)=-1",1,0.999597
1,19,"gpa_bin0_[0.000,0.476)=+1 AND\nzfygpa_bin3_[0.607,1.000)=+1 AND\nlsat_bin0_[0.000,0.463)=+1 AND\nlsat_bin1_[0.463,0.612)=-1",1,0.958838
2,9,"gpa_bin3_[0.762,1.000)=+1 AND\nzfygpa_bin3_[0.607,1.000)=+1 AND\ngpa_bin0_[0.000,0.476)=+1 AND\nzfygpa_bin1_[0.376,0.484)=+1",1,0.944675
3,17,"gpa_bin1_[0.476,0.619)=+1 AND\nzfygpa_bin0_[0.000,0.376)=+1 AND\nlsat_bin3_[0.731,1.000)=-1 AND\nzfygpa_bin1_[0.376,0.484)=+1",0,0.940117
4,13,"lsat_bin3_[0.731,1.000)=-1 AND\ngpa_bin1_[0.476,0.619)=+1 AND\nzfygpa_bin1_[0.376,0.484)=+1 AND\ngpa_bin0_[0.000,0.476)=-1",1,0.922294
5,4,"lsat_bin3_[0.731,1.000)=+1 AND\nzfygpa_bin2_[0.484,0.607)=+1 AND\nlsat_bin2_[0.612,0.731)=-1 AND\nlsat_bin1_[0.463,0.612)=-1",0,0.889179
6,21,"zfygpa_bin1_[0.376,0.484)=+1 AND\nlsat_bin0_[0.000,0.463)=+1 AND\ngpa_bin2_[0.619,0.762)=-1 AND\nzfygpa_bin3_[0.607,1.000)=+1",0,0.858647
7,18,"lsat_bin3_[0.731,1.000)=+1 AND\ngpa_bin3_[0.762,1.000)=-1 AND\nlsat_bin1_[0.463,0.612)=-1 AND\nlsat_bin2_[0.612,0.731)=+1",0,0.852749
8,22,"lsat_bin2_[0.612,0.731)=-1 AND\nzfygpa_bin2_[0.484,0.607)=+1 AND\nzfygpa_bin1_[0.376,0.484)=-1 AND\ngpa_bin0_[0.000,0.476)=+1",0,0.830300
9,15,"zfygpa_bin1_[0.376,0.484)=+1 AND\nlsat_bin3_[0.731,1.000)=+1 AND\nlsat_bin0_[0.000,0.463)=+1 AND\nzfygpa_bin3_[0.607,1.000)=-1",0,0.812145

### `hyconex/moons` — contrefactuels

,sample,true,pred,target,valid_cf,n_flips,flips
0,135,1.0,1.0,0.0,1,5,"f0_bin0_[0.000,0.337): -1 → 1; f0_bin1_[0.337,0.498): -1 → 1; f0_bin2_[0.498,0.676): -1 → 1; f1_bin1_[0.289,0.511): ..."
1,17,1.0,1.0,0.0,1,4,"f0_bin0_[0.000,0.337): -1 → 1; f0_bin3_[0.676,1.000): -1 → 1; f1_bin2_[0.511,0.732): 1 → -1; f1_bin3_[0.732,1.000): ..."
2,158,0.0,0.0,1.0,1,3,"f0_bin0_[0.000,0.337): -1 → 1; f0_bin2_[0.498,0.676): -1 → 1; f0_bin3_[0.676,1.000): -1 → 1"

### `hyconex/moons` — règles HyperLogic (top 10)

,rule_id,if,then_class,score
0,19,"f1_bin0_[0.000,0.289)=-1 AND\nf1_bin1_[0.289,0.511)=-1 AND\nf1_bin2_[0.511,0.732)=-1 AND\nf1_bin3_[0.732,1.000)=+1",0.0,0.999994
1,8,"f1_bin0_[0.000,0.289)=+1 AND\nf1_bin1_[0.289,0.511)=+1 AND\nf1_bin3_[0.732,1.000)=+1 AND\nf0_bin2_[0.498,0.676)=-1",1.0,0.999983
2,17,"f1_bin2_[0.511,0.732)=-1 AND\nf0_bin0_[0.000,0.337)=-1 AND\nf1_bin0_[0.000,0.289)=+1 AND\nf1_bin1_[0.289,0.511)=+1",1.0,0.999977
3,23,"f1_bin2_[0.511,0.732)=+1 AND\nf1_bin3_[0.732,1.000)=+1 AND\nf0_bin0_[0.000,0.337)=+1 AND\nf0_bin2_[0.498,0.676)=-1",0.0,0.999935
4,9,"f0_bin3_[0.676,1.000)=-1 AND\nf1_bin1_[0.289,0.511)=+1 AND\nf0_bin1_[0.337,0.498)=+1 AND\nf1_bin3_[0.732,1.000)=-1",1.0,0.999812
5,14,"f1_bin0_[0.000,0.289)=-1 AND\nf1_bin3_[0.732,1.000)=+1 AND\nf0_bin2_[0.498,0.676)=-1 AND\nf1_bin2_[0.511,0.732)=-1",0.0,0.999734
6,4,"f1_bin2_[0.511,0.732)=+1 AND\nf0_bin0_[0.000,0.337)=-1 AND\nf1_bin0_[0.000,0.289)=-1 AND\nf0_bin2_[0.498,0.676)=+1",0.0,0.999724
7,16,"f0_bin1_[0.337,0.498)=+1 AND\nf0_bin3_[0.676,1.000)=-1 AND\nf1_bin3_[0.732,1.000)=-1 AND\nf0_bin0_[0.000,0.337)=-1",1.0,0.999544
8,6,"f1_bin0_[0.000,0.289)=+1 AND\nf1_bin2_[0.511,0.732)=-1 AND\nf1_bin3_[0.732,1.000)=-1 AND\nf0_bin1_[0.337,0.498)=-1",1.0,0.999481
9,0,"f0_bin2_[0.498,0.676)=+1 AND\nf1_bin2_[0.511,0.732)=-1 AND\nf0_bin3_[0.676,1.000)=+1 AND\nf1_bin1_[0.289,0.511)=-1",1.0,0.999412

### `hyconex/moons_with_blob` — contrefactuels

,sample,true,pred,target,valid_cf,n_flips,flips
0,134,0.0,0.0,1.0,1,3,"-0.15681690615571184_bin1_[0.297,0.382): 1 → -1; -0.15681690615571184_bin3_[0.515,1.000): -1 → 1; 0.3147027677510667..."
1,17,0.0,0.0,1.0,1,3,"-0.15681690615571184_bin0_[0.000,0.297): 1 → -1; -0.15681690615571184_bin3_[0.515,1.000): -1 → 1; 0.3147027677510667..."
2,156,1.0,1.0,0.0,1,3,"-0.15681690615571184_bin3_[0.515,1.000): -1 → 1; 0.31470276775106676_bin1_[0.171,0.438): -1 → 1; 0.31470276775106676..."

### `hyconex/moons_with_blob` — règles HyperLogic (top 10)

,rule_id,if,then_class,score
0,5,"0.31470276775106676_bin1_[0.171,0.438)=+1 AND\n0.31470276775106676_bin2_[0.438,0.516)=-1 AND\n0.31470276775106676_bin3_[0.516,1.000)=+1 AND\n-0.15681690615571184_bin2_[0.382,0.515)=+1",0.0,0.995655
1,1,"0.31470276775106676_bin2_[0.438,0.516)=+1 AND\n0.31470276775106676_bin1_[0.171,0.438)=-1 AND\n0.31470276775106676_bin3_[0.516,1.000)=-1 AND\n0.31470276775106676_bin0_[0.000,0.171)=-1",0.0,0.989873
2,8,"0.31470276775106676_bin0_[0.000,0.171)=+1 AND\n-0.15681690615571184_bin2_[0.382,0.515)=+1 AND\n-0.15681690615571184_bin3_[0.515,1.000)=+1 AND\n0.31470276775106676_bin3_[0.516,1.000)=+1",0.0,0.982810
3,47,"-0.15681690615571184_bin0_[0.000,0.297)=+1 AND\n0.31470276775106676_bin1_[0.171,0.438)=-1 AND\n0.31470276775106676_bin3_[0.516,1.000)=-1 AND\n0.31470276775106676_bin2_[0.438,0.516)=+1",0.0,0.982599
4,53,"-0.15681690615571184_bin3_[0.515,1.000)=-1 AND\n0.31470276775106676_bin1_[0.171,0.438)=-1 AND\n0.31470276775106676_bin3_[0.516,1.000)=-1 AND\n-0.15681690615571184_bin2_[0.382,0.515)=+1",1.0,0.977334
5,36,"0.31470276775106676_bin1_[0.171,0.438)=-1 AND\n0.31470276775106676_bin3_[0.516,1.000)=-1 AND\n-0.15681690615571184_bin0_[0.000,0.297)=-1 AND\n0.31470276775106676_bin0_[0.000,0.171)=+1",1.0,0.976244
6,55,"-0.15681690615571184_bin3_[0.515,1.000)=-1 AND\n0.31470276775106676_bin0_[0.000,0.171)=+1 AND\n-0.15681690615571184_bin1_[0.297,0.382)=-1 AND\n0.31470276775106676_bin3_[0.516,1.000)=-1",1.0,0.971860
7,46,"0.31470276775106676_bin0_[0.000,0.171)=+1 AND\n0.31470276775106676_bin2_[0.438,0.516)=-1 AND\n-0.15681690615571184_bin3_[0.515,1.000)=-1 AND\n-0.15681690615571184_bin2_[0.382,0.515)=-1",1.0,0.966552
8,18,"-0.15681690615571184_bin3_[0.515,1.000)=-1 AND\n0.31470276775106676_bin0_[0.000,0.171)=+1 AND\n-0.15681690615571184_bin2_[0.382,0.515)=+1 AND\n0.31470276775106676_bin2_[0.438,0.516)=-1",1.0,0.950381
9,21,"0.31470276775106676_bin0_[0.000,0.171)=+1 AND\n0.31470276775106676_bin1_[0.171,0.438)=+1 AND\n-0.15681690615571184_bin3_[0.515,1.000)=+1 AND\n-0.15681690615571184_bin0_[0.000,0.297)=-1",0.0,0.949393

### `hyperlogic/brca-n` — contrefactuels

,sample,true,pred,target,valid_cf,n_flips,flips
0,31,tumor,tumor,normal,0,69,"ENSG00000102048_bin0_[0.000,1.000): 1 → -1; ENSG00000198963_bin0_[0.000,1.000): 1 → -1; ENSG00000104765_bin0_[0.000,..."
1,1,tumor,tumor,normal,0,69,"ENSG00000102048_bin0_[0.000,1.000): 1 → -1; ENSG00000198963_bin0_[0.000,1.000): 1 → -1; ENSG00000104765_bin0_[0.000,..."
2,33,tumor,tumor,normal,0,69,"ENSG00000102048_bin0_[0.000,1.000): 1 → -1; ENSG00000198963_bin0_[0.000,1.000): 1 → -1; ENSG00000104765_bin0_[0.000,..."

### `hyperlogic/brca-n` — règles HyperLogic (top 10)

,rule_id,if,then_class,score
0,60,"ENSG00000112293_bin0_[0.000,1.000)=-1 AND\nENSG00000171097_bin0_[0.000,1.000)=-1 AND\nENSG00000111832_bin0_[0.000,1.000)=+1 AND\nENSG00000152910_bin0_[0.000,1.000)=+1",tumor,0.969032
1,38,"ENSG00000164327_bin0_[0.000,1.000)=-1 AND\nENSG00000102893_bin0_[0.000,1.000)=-1 AND\nENSG00000065413_bin0_[0.000,1.000)=-1 AND\nENSG00000166123_bin0_[0.000,1.000)=+1",tumor,0.963785
2,44,"ENSG00000102048_bin0_[0.000,1.000)=+1 AND\nENSG00000102893_bin0_[0.000,1.000)=+1 AND\nENSG00000198963_bin0_[0.000,1.000)=-1 AND\nENSG00000047634_bin0_[0.000,1.000)=+1",tumor,0.951211
3,37,"ENSG00000066027_bin0_[0.000,1.000)=+1 AND\nENSG00000171560_bin0_[0.000,1.000)=+1 AND\nENSG00000102893_bin0_[0.000,1.000)=-1 AND\nENSG00000102048_bin0_[0.000,1.000)=+1",normal,0.948548
4,10,"ENSG00000164292_bin0_[0.000,1.000)=-1 AND\nENSG00000166479_bin0_[0.000,1.000)=+1 AND\nENSG00000108684_bin0_[0.000,1.000)=-1 AND\nENSG00000103546_bin0_[0.000,1.000)=+1",normal,0.937887
5,12,"ENSG00000168904_bin0_[0.000,1.000)=+1 AND\nENSG00000115604_bin0_[0.000,1.000)=-1 AND\nENSG00000095574_bin0_[0.000,1.000)=+1 AND\nENSG00000136802_bin0_[0.000,1.000)=+1",normal,0.931704
6,30,"ENSG00000115604_bin0_[0.000,1.000)=-1 AND\nENSG00000157093_bin0_[0.000,1.000)=+1 AND\nENSG00000198963_bin0_[0.000,1.000)=+1 AND\nENSG00000198130_bin0_[0.000,1.000)=-1",tumor,0.919566
7,45,"ENSG00000123411_bin0_[0.000,1.000)=-1 AND\nENSG00000127481_bin0_[0.000,1.000)=-1 AND\nENSG00000185689_bin0_[0.000,1.000)=-1 AND\nENSG00000175879_bin0_[0.000,1.000)=+1",normal,0.914179
8,42,"ENSG00000136802_bin0_[0.000,1.000)=+1 AND\nENSG00000124588_bin0_[0.000,1.000)=-1 AND\nENSG00000095574_bin0_[0.000,1.000)=+1 AND\nENSG00000145975_bin0_[0.000,1.000)=+1",tumor,0.910434
9,13,"ENSG00000102359_bin0_[0.000,1.000)=+1 AND\nENSG00000153157_bin0_[0.000,1.000)=-1 AND\nENSG00000112294_bin0_[0.000,1.000)=-1 AND\nENSG00000064989_bin0_[0.000,1.000)=+1",normal,0.909982

### `hyperlogic/brca-s` — contrefactuels

,sample,true,pred,target,valid_cf,n_flips,flips
0,37,3,3,0,0,53,"ENSG00000176887_bin0_[0.000,1.000): 1 → -1; ENSG00000143546_bin0_[0.000,1.000): 1 → -1; ENSG00000254726_bin0_[0.000,..."
1,37,3,3,1,0,50,"ENSG00000176887_bin0_[0.000,1.000): 1 → -1; ENSG00000143546_bin0_[0.000,1.000): 1 → -1; ENSG00000254726_bin0_[0.000,..."
2,37,3,3,2,0,50,"ENSG00000176887_bin0_[0.000,1.000): 1 → -1; ENSG00000143546_bin0_[0.000,1.000): 1 → -1; ENSG00000254726_bin0_[0.000,..."
3,0,3,3,0,0,53,"ENSG00000176887_bin0_[0.000,1.000): 1 → -1; ENSG00000143546_bin0_[0.000,1.000): 1 → -1; ENSG00000254726_bin0_[0.000,..."
4,0,3,3,1,0,50,"ENSG00000176887_bin0_[0.000,1.000): 1 → -1; ENSG00000143546_bin0_[0.000,1.000): 1 → -1; ENSG00000254726_bin0_[0.000,..."
5,0,3,3,2,0,50,"ENSG00000176887_bin0_[0.000,1.000): 1 → -1; ENSG00000143546_bin0_[0.000,1.000): 1 → -1; ENSG00000254726_bin0_[0.000,..."
6,33,3,3,0,0,53,"ENSG00000176887_bin0_[0.000,1.000): 1 → -1; ENSG00000143546_bin0_[0.000,1.000): 1 → -1; ENSG00000254726_bin0_[0.000,..."
7,33,3,3,1,0,50,"ENSG00000176887_bin0_[0.000,1.000): 1 → -1; ENSG00000143546_bin0_[0.000,1.000): 1 → -1; ENSG00000254726_bin0_[0.000,..."
8,33,3,3,2,0,50,"ENSG00000176887_bin0_[0.000,1.000): 1 → -1; ENSG00000143546_bin0_[0.000,1.000): 1 → -1; ENSG00000254726_bin0_[0.000,..."

### `hyperlogic/brca-s` — règles HyperLogic (top 10)

,rule_id,if,then_class,score
0,51,"ENSG00000168539_bin0_[0.000,1.000)=-1 AND\nENSG00000119866_bin0_[0.000,1.000)=-1 AND\nENSG00000170442_bin0_[0.000,1.000)=+1 AND\nENSG00000014257_bin0_[0.000,1.000)=-1",0,0.850503
1,18,"ENSG00000102243_bin0_[0.000,1.000)=+1 AND\nENSG00000159556_bin0_[0.000,1.000)=-1 AND\nENSG00000115221_bin0_[0.000,1.000)=+1 AND\nENSG00000170178_bin0_[0.000,1.000)=-1",2,0.846271
2,22,"ENSG00000168268_bin0_[0.000,1.000)=+1 AND\nENSG00000175183_bin0_[0.000,1.000)=+1 AND\nENSG00000058335_bin0_[0.000,1.000)=+1 AND\nENSG00000054598_bin0_[0.000,1.000)=+1",1,0.828058
3,40,"ENSG00000178372_bin0_[0.000,1.000)=+1 AND\nENSG00000178750_bin0_[0.000,1.000)=-1 AND\nENSG00000115596_bin0_[0.000,1.000)=-1 AND\nENSG00000183421_bin0_[0.000,1.000)=-1",0,0.825561
4,5,"ENSG00000173894_bin0_[0.000,1.000)=+1 AND\nENSG00000135069_bin0_[0.000,1.000)=+1 AND\nENSG00000102900_bin0_[0.000,1.000)=+1 AND\nENSG00000182379_bin0_[0.000,1.000)=-1",0,0.789326
5,45,"ENSG00000176597_bin0_[0.000,1.000)=-1 AND\nENSG00000159556_bin0_[0.000,1.000)=-1 AND\nENSG00000053524_bin0_[0.000,1.000)=+1 AND\nENSG00000126878_bin0_[0.000,1.000)=+1",0,0.737020
6,62,"ENSG00000119812_bin0_[0.000,1.000)=+1 AND\nENSG00000160209_bin0_[0.000,1.000)=+1 AND\nENSG00000137309_bin0_[0.000,1.000)=+1 AND\nENSG00000148842_bin0_[0.000,1.000)=+1",0,0.731800
7,44,"ENSG00000197696_bin0_[0.000,1.000)=-1 AND\nENSG00000105173_bin0_[0.000,1.000)=+1 AND\nENSG00000135069_bin0_[0.000,1.000)=-1 AND\nENSG00000013619_bin0_[0.000,1.000)=+1",1,0.710968
8,50,"ENSG00000065978_bin0_[0.000,1.000)=-1 AND\nENSG00000148842_bin0_[0.000,1.000)=-1 AND\nENSG00000102996_bin0_[0.000,1.000)=-1 AND\nENSG00000164638_bin0_[0.000,1.000)=-1",2,0.705794
9,23,"ENSG00000013619_bin0_[0.000,1.000)=-1 AND\nENSG00000198074_bin0_[0.000,1.000)=-1 AND\nENSG00000171234_bin0_[0.000,1.000)=-1 AND\nENSG00000143546_bin0_[0.000,1.000)=-1",3,0.684496

### `hyperlogic/cardio` — contrefactuels

,sample,true,pred,target,valid_cf,n_flips,flips
0,9171,1,1,0,1,14,"age_bin0_[0.000,0.529): -1 → 1; height_bin1_[0.528,0.560): -1 → 1; weight_bin0_[0.000,0.286): -1 → 1; weight_bin2_[0..."
1,1296,0,0,1,1,20,"age_bin0_[0.000,0.529): -1 → 1; height_bin1_[0.528,0.560): -1 → 1; height_bin2_[0.560,0.585): -1 → 1; height_bin3_[0..."
2,10819,0,0,1,1,18,"age_bin2_[0.676,0.824): -1 → 1; height_bin1_[0.528,0.560): -1 → 1; height_bin2_[0.560,0.585): -1 → 1; height_bin3_[0..."

### `hyperlogic/cardio` — règles HyperLogic (top 10)

,rule_id,if,then_class,score
0,38,"age_bin2_[0.676,0.824)=+1 AND\nap_lo_bin1_[0.014,0.014)=-1 AND\nap_hi_bin2_[0.018,1.000)=+1 AND\nweight_bin2_[0.323,0.376)=+1",1,0.999999
1,34,"gender=2=-1 AND\nage_bin0_[0.000,0.529)=-1 AND\ngluc=2=-1 AND\nap_hi_bin2_[0.018,1.000)=-1",0,0.999883
2,15,"ap_hi_bin2_[0.018,1.000)=+1 AND\nheight_bin2_[0.560,0.585)=+1 AND\nap_lo_bin0_[0.000,0.014)=+1 AND\ngluc=3=-1",0,0.999420
3,61,"gluc=2=+1 AND\nap_lo_bin0_[0.000,0.014)=-1 AND\nage_bin0_[0.000,0.529)=+1 AND\ncholesterol=1=-1",0,0.999083
4,37,"smoke=0=-1 AND\nalco=1=+1 AND\nheight_bin0_[0.000,0.528)=+1 AND\nactive=1=-1",0,0.999070
5,28,"height_bin3_[0.585,1.000)=-1 AND\ngluc=1=-1 AND\ngluc=3=+1 AND\nap_hi_bin0_[0.000,0.017)=+1",1,0.997808
6,62,"smoke=1=+1 AND\nap_lo_bin1_[0.014,0.014)=+1 AND\ncholesterol=2=+1 AND\nap_hi_bin0_[0.000,0.017)=+1",1,0.997611
7,6,"height_bin0_[0.000,0.528)=-1 AND\ncholesterol=1=-1 AND\ncholesterol=2=+1 AND\nage_bin0_[0.000,0.529)=+1",0,0.996992
8,17,"gender=1=-1 AND\ncholesterol=2=+1 AND\nap_lo_bin2_[0.014,1.000)=-1 AND\nap_hi_bin1_[0.017,0.018)=+1",0,0.994629
9,30,"ap_hi_bin1_[0.017,0.018)=-1 AND\nactive=0=+1 AND\nap_lo_bin1_[0.014,0.014)=-1 AND\nap_lo_bin2_[0.014,1.000)=+1",0,0.993584

### `hyperlogic/disease` — contrefactuels

,sample,true,pred,target,valid_cf,n_flips,flips
0,644,39,39,0,0,60,symptom=acute_liver_failure: -1 → 1; symptom=anxiety: -1 → 1; symptom=back_pain: -1 → 1; symptom=belly_pain: -1 → 1;...
1,644,39,39,1,0,59,symptom=acute_liver_failure: -1 → 1; symptom=anxiety: -1 → 1; symptom=back_pain: -1 → 1; symptom=belly_pain: -1 → 1;...
2,644,39,39,2,0,58,symptom=acute_liver_failure: -1 → 1; symptom=anxiety: -1 → 1; symptom=back_pain: -1 → 1; symptom=belly_pain: -1 → 1;...
3,644,39,39,3,0,59,symptom=acute_liver_failure: -1 → 1; symptom=anxiety: -1 → 1; symptom=back_pain: -1 → 1; symptom=belly_pain: -1 → 1;...
4,644,39,39,4,0,60,symptom=acute_liver_failure: -1 → 1; symptom=anxiety: -1 → 1; symptom=back_pain: -1 → 1; symptom=belly_pain: -1 → 1;...
...,...,...,...,...,...,...,...
115,760,3,3,36,0,58,symptom=abnormal_menstruation: -1 → 1; symptom=belly_pain: -1 → 1; symptom=bladder_discomfort: -1 → 1; symptom=blood...
116,760,3,3,37,0,60,symptom=abnormal_menstruation: -1 → 1; symptom=acidity: -1 → 1; symptom=belly_pain: -1 → 1; symptom=bladder_discomfo...
117,760,3,3,38,0,62,symptom=abnormal_menstruation: -1 → 1; symptom=acidity: -1 → 1; symptom=belly_pain: -1 → 1; symptom=bladder_discomfo...
118,760,3,3,39,0,56,symptom=abnormal_menstruation: -1 → 1; symptom=belly_pain: -1 → 1; symptom=bladder_discomfort: -1 → 1; symptom=blood...
119,760,3,3,40,0,61,symptom=abnormal_menstruation: -1 → 1; symptom=belly_pain: -1 → 1; symptom=bladder_discomfort: -1 → 1; symptom=blood...

### `hyperlogic/disease` — règles HyperLogic (top 10)

,rule_id,if,then_class,score
0,73,symptom=dark_urine=-1 AND\nsymptom=acute_liver_failure=-1 AND\nsymptom=yellowish_skin=-1 AND\nsymptom=blurred_and_distorted_vision=-1,7,0.371347
1,5,symptom=phlegm=-1 AND\nsymptom=puffy_face_and_eyes=-1 AND\nsymptom=depression=+1 AND\nsymptom=coma=-1,11,0.276325
2,71,symptom=mood_swings=-1 AND\nsymptom=extra_marital_contacts=+1 AND\nsymptom=enlarged_thyroid=+1 AND\nsymptom=brittle_nails=-1,16,0.259902
3,74,symptom=increased_appetite=-1 AND\nsymptom=cold_hands_and_feets=+1 AND\nsymptom=back_pain=+1 AND\nsymptom=prominent_veins_on_calf=-1,13,0.212892
4,68,symptom=dehydration=-1 AND\nsymptom=chills=+1 AND\nsymptom=cold_hands_and_feets=-1 AND\nsymptom=drying_and_tingling_lips=+1,36,0.210217
5,4,symptom=prominent_veins_on_calf=+1 AND\nsymptom=nausea=-1 AND\nsymptom=dehydration=-1 AND\nsymptom=pain_behind_the_eyes=+1,15,0.202299
6,7,symptom=watering_from_eyes=-1 AND\nsymptom=receiving_unsterile_injections=-1 AND\nsymptom=anxiety=-1 AND\nsymptom=nausea=+1,23,0.199088
7,32,symptom=coma=+1 AND\nsymptom=inflammatory_nails=+1 AND\nsymptom=weakness_in_limbs=+1 AND\nsymptom=phlegm=-1,20,0.190549
8,9,symptom=sinus_pressure=-1 AND\nsymptom=lethargy=-1 AND\nsymptom=dark_urine=+1 AND\nsymptom=vomiting=-1,22,0.182576
9,69,symptom=foul_smell_of urine=+1 AND\nsymptom=bruising=-1 AND\nsymptom=brittle_nails=+1 AND\nsymptom=pain_in_anal_region=-1,21,0.172180

## Exemple de règle complète (premier jeu entraîné)

In [7]:
if runs:
    first = next(iter(runs.values()))
    if first['rules']:
        rule = first['rules'][0]
        print('Jeu =', first['key'])
        print('rule_id =', rule.get('rule_id'))
        print('then_class =', rule.get('then_class'))
        print('score =', rule.get('score'))
        print('\nIF')
        for cond in rule.get('if', []):
            print(' ', cond)
        print('THEN →', rule.get('then_class'))

Jeu = hyconex/adult
rule_id = 41
then_class = 0
score = 1.0

IF
  marital_status=Single=+1
  education=Prof-school=-1
  marital_status=Married=-1
  education=HS-grad=-1
THEN → 0