# TabResNet DLBAC — HyConEx / HyperLogic datasets

Deuxième notebook : **dernière version du modèle** (`TabResNetDLBACTrainer`).

| Dimension entrée | Stratégie |
|---|---|
| ≤ 512 features | **instance** — TabResNet par échantillon + DR-Net + CF binaire (Dry Bean) |
| > 512 features | **bipolar_hyper** — encodeur + hyper TabResNet 78% + règles DR-Net 22% + CF continu |

**Jeux** : `HyConEx/data/` + `HyperLogic/data/` (même chargeurs que le notebook DR-HyperCF).

**Prétraitement** : continus → intervalles ; catégorielles → one-hot ; puis bipolarisation.

Pour chaque jeu : métriques, mode utilisé, contrefactuels et règles.

In [1]:
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from IPython.display import Markdown, display

ROOT = Path.cwd().resolve().parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from hyconex_hyperlogic_datasets import list_available_datasets
from hyconex_pure_bipolar import explain_counterfactual_bipolar
from hyconex_pure_bipolar.bipolar import continuous_to_bipolar
from tabresnet_dlbac import TabResNetDLBACConfig, TabResNetDLBACTrainer
from tabular_mixed_preprocessing import TabularDatasetSplits, get_dataset_loaders

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Device:', device)
print('Jeux détectés:', list_available_datasets())

Device: cuda
Jeux détectés: {'hyconex': ['adult', 'audit', 'blobs', 'compas', 'german_credit', 'heloc', 'law', 'moons', 'wine', 'moons_with_blob'], 'hyperlogic': ['cardio', 'disease', 'brca-n', 'brca-s']}

## Configuration

In [2]:
ALL_LOADERS = get_dataset_loaders()

DATASETS = None  # None = tous ; ex. ['hyconex/adult', 'hyperlogic/cardio']
if DATASETS is None:
    DATASETS = sorted(ALL_LOADERS.keys())

SEED = 42
QUICK_RUN = False
MAX_INSTANCE_DIM = 512

print(f'{len(DATASETS)} jeux:', DATASETS)

14 jeux: ['hyconex/adult', 'hyconex/audit', 'hyconex/blobs', 'hyconex/compas', 'hyconex/german_credit', 'hyconex/heloc', 'hyconex/law', 'hyconex/moons', 'hyconex/moons_with_blob', 'hyconex/wine', 'hyperlogic/brca-n', 'hyperlogic/brca-s', 'hyperlogic/cardio', 'hyperlogic/disease']

In [3]:
def make_tabresnet_config(splits: TabularDatasetSplits) -> TabResNetDLBACConfig:
    n_feat = splits.X_train.shape[1]
    n_classes = len(splits.class_names)
    high = n_feat > MAX_INSTANCE_DIM

    inst_epochs = 8 if QUICK_RUN else (45 if n_feat < 100 else 35)
    bipolar_epochs = 6 if QUICK_RUN else (50 if high else 40)

    return TabResNetDLBACConfig(
        seed=SEED,
        max_instance_dim=MAX_INSTANCE_DIM,
        instance_epochs=inst_epochs,
        instance_batch_size=128,
        instance_num_rules=min(128, 32 + 6 * n_classes),
        instance_temperature=0.7,
        instance_cf_lambda=0.10 if n_classes > 2 else 0.15,
        instance_flip_lambda=0.05,
        instance_cf_warmup=2 if not QUICK_RUN else 0,
        embed_epochs=bipolar_epochs,
        embed_batch_size=96 if high else 64,
        embed_num_rules=48,
        hyper_hidden_dim=128,
        input_encoding=splits.input_encoding,
        early_stop_metric='auto',
    )


def train_on_dataset(key: str) -> dict:
    splits = ALL_LOADERS[key]()
    cfg = make_tabresnet_config(splits)
    trainer = TabResNetDLBACTrainer(cfg, device=device)

    print(f"\n{'=' * 72}\n{key} | train {splits.X_train.shape} | classes {len(splits.class_names)}\n{'=' * 72}")

    result = trainer.fit(
        splits.X_train,
        splits.y_train,
        x_val=splits.X_val,
        y_val=splits.y_val,
        feature_names=splits.feature_names,
        class_names=splits.class_names,
        verbose=True,
    )
    metrics = trainer.evaluate(splits.X_test, splits.y_test, counterfactuals=True)
    rules = trainer.export_rules(top_per_rule=4, min_abs_weight=0.05)

    return {
        'key': key,
        'splits': splits,
        'trainer': trainer,
        'result': result,
        'metrics': metrics,
        'rules': rules,
    }


def metrics_row(run: dict) -> dict:
    m = run['metrics']
    cf = m.get('counterfactuals', {})
    return {
        'dataset': run['key'],
        'mode': run['result'].mode,
        'best_val_acc': run['result'].best_val_accuracy,
        'best_val_auroc': run['result'].best_val_auroc,
        'test_acc': m.get('accuracy'),
        'test_auroc': m.get('auroc_ovr'),
        'cf_validity': cf.get('validity_cf'),
        'cf_changed_bits': cf.get('changed_bits_mean', cf.get('hamming_mean')),
        'cf_l1': cf.get('proximity_l1_cont_mean', cf.get('proximity_l1_mean')),
        'n_rules': len(run['rules']),
    }

## Entraînement

In [4]:
runs: dict[str, dict] = {}
failures: dict[str, str] = {}

for ds_key in DATASETS:
    try:
        runs[ds_key] = train_on_dataset(ds_key)
    except Exception as exc:
        failures[ds_key] = str(exc)
        print('ERREUR', ds_key, '→', exc)

if runs:
    summary_df = pd.DataFrame([metrics_row(r) for r in runs.values()])
    display(summary_df.round(4))
else:
    print('Aucun jeu entraîné.')

if failures:
    print('\nÉchecs:')
    for k, v in failures.items():
        print('-', k, ':', v)

========================================================================
hyconex/adult | train (20838, 34) | classes 2
========================================================================
  Strategie: TabResNet instance (HybridDRNetModel)
[Epoch 001/45] [warmup] loss=0.4794 val_acc=0.7658 val_auroc=0.8791 best(accuracy)=0.7658
[Epoch 002/45] [warmup] loss=0.4413 val_acc=0.7397 val_auroc=0.8793 best(accuracy)=0.7658
[Epoch 003/45] loss=0.5794 val_acc=0.8042 val_auroc=0.8780 best(accuracy)=0.8042
[Epoch 004/45] loss=0.5192 val_acc=0.7620 val_auroc=0.8795 best(accuracy)=0.8042
[Epoch 005/45] loss=0.5079 val_acc=0.8259 val_auroc=0.8812 best(accuracy)=0.8259
[Epoch 006/45] loss=0.5013 val_acc=0.7572 val_auroc=0.8798 best(accuracy)=0.8259
[Epoch 007/45] loss=0.4963 val_acc=0.7808 val_auroc=0.8802 best(accuracy)=0.8259
[Epoch 008/45] loss=0.4965 val_acc=0.7764 val_auroc=0.8793 best(accuracy)=0.8259
[Epoch 009/45] loss=0.4952 val_acc=0.7553 val_auroc=0.8781 best(accuracy)=0.8259
[Epoch 010/45] loss=0.4970 val_acc=0.7764 val_auroc=0.8799 best(accuracy)=0.8259
[Epoch 011/45] loss=0.4873 val_acc=0.7672 val_auroc=0.8811 best(accuracy)=0.8259
[Epoch 012/45] loss=0.5318 val_acc=0.7628 val_auroc=0.8797 best(accuracy)=0.8259
[Epoch 013/45] loss=0.6235 val_acc=0.7779 val_auroc=0.8802 best(accuracy)=0.8259
[Epoch 014/45] loss=0.5819 val_acc=0.7990 val_auroc=0.8795 best(accuracy)=0.8259
[Epoch 015/45] loss=0.6010 val_acc=0.7670 val_auroc=0.8797 best(accuracy)=0.8259
[Epoch 016/45] loss=0.4888 val_acc=0.7893 val_auroc=0.8786 best(accuracy)=0.8259
[Epoch 017/45] loss=0.4895 val_acc=0.7601 val_auroc=0.8779 best(accuracy)=0.8259
[Epoch 018/45] loss=0.4798 val_acc=0.7687 val_auroc=0.8779 best(accuracy)=0.8259
[Epoch 019/45] loss=0.4783 val_acc=0.7605 val_auroc=0.8781 best(accuracy)=0.8259
[Epoch 020/45] loss=0.4721 val_acc=0.7825 val_auroc=0.8771 best(accuracy)=0.8259
[Epoch 021/45] loss=0.4719 val_acc=0.7695 val_auroc=0.8765 best(accuracy)=0.8259
[Epoch 022/45] loss=0.4715 val_acc=0.7702 val_auroc=0.8763 best(accuracy)=0.8259
[Epoch 023/45] loss=0.4705 val_acc=0.7724 val_auroc=0.8774 best(accuracy)=0.8259
[Epoch 024/45] loss=0.4896 val_acc=0.6862 val_auroc=0.8746 best(accuracy)=0.8259
[Epoch 025/45] loss=0.4755 val_acc=0.7818 val_auroc=0.8748 best(accuracy)=0.8259
[Epoch 026/45] loss=0.4617 val_acc=0.7724 val_auroc=0.8727 best(accuracy)=0.8259
[Epoch 027/45] loss=0.4602 val_acc=0.7637 val_auroc=0.8676 best(accuracy)=0.8259
[Epoch 028/45] loss=0.4565 val_acc=0.7631 val_auroc=0.8709 best(accuracy)=0.8259
[Epoch 029/45] loss=0.4580 val_acc=0.7549 val_auroc=0.8658 best(accuracy)=0.8259
[Epoch 030/45] loss=0.4550 val_acc=0.7593 val_auroc=0.8703 best(accuracy)=0.8259
[Epoch 031/45] loss=0.4978 val_acc=0.6858 val_auroc=0.8712 best(accuracy)=0.8259
[Epoch 032/45] loss=0.4667 val_acc=0.7664 val_auroc=0.8690 best(accuracy)=0.8259
[Epoch 033/45] loss=0.4502 val_acc=0.7568 val_auroc=0.8622 best(accuracy)=0.8259
[Epoch 034/45] loss=0.4435 val_acc=0.7864 val_auroc=0.8668 best(accuracy)=0.8259
[Epoch 035/45] loss=0.4725 val_acc=0.7434 val_auroc=0.8701 best(accuracy)=0.8259
[Epoch 036/45] loss=0.4393 val_acc=0.7618 val_auroc=0.8674 best(accuracy)=0.8259
[Epoch 037/45] loss=0.4380 val_acc=0.7562 val_auroc=0.8609 best(accuracy)=0.8259
[Epoch 038/45] loss=0.4371 val_acc=0.7875 val_auroc=0.8626 best(accuracy)=0.8259
[Epoch 039/45] loss=0.4348 val_acc=0.7798 val_auroc=0.8590 best(accuracy)=0.8259
[Epoch 040/45] loss=0.4347 val_acc=0.7585 val_auroc=0.8589 best(accuracy)=0.8259
[Epoch 041/45] loss=0.4307 val_acc=0.7595 val_auroc=0.8583 best(accuracy)=0.8259
[Epoch 042/45] loss=0.4312 val_acc=0.7683 val_auroc=0.8622 best(accuracy)=0.8259
[Epoch 043/45] loss=0.4291 val_acc=0.7868 val_auroc=0.8590 best(accuracy)=0.8259
[Epoch 044/45] loss=0.4266 val_acc=0.7570 val_auroc=0.8597 best(accuracy)=0.8259
[Epoch 045/45] loss=0.4265 val_acc=0.7670 val_auroc=0.8554 best(accuracy)=0.8259
  binarizer mode=bipolar | early_stop=accuracy

========================================================================
hyconex/audit | train (390, 23) | classes 2
========================================================================
  Strategie: TabResNet instance (HybridDRNetModel)
[Epoch 001/45] [warmup] loss=0.4630 val_acc=0.9184 val_auroc=0.9917 best(accuracy)=0.9184
[Epoch 002/45] [warmup] loss=0.0981 val_acc=0.9796 val_auroc=1.0000 best(accuracy)=0.9796
[Epoch 003/45] loss=0.9009 val_acc=1.0000 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 004/45] loss=0.5354 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 005/45] loss=0.5498 val_acc=1.0000 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 006/45] loss=0.5054 val_acc=1.0000 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 007/45] loss=0.4989 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 008/45] loss=0.5019 val_acc=1.0000 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 009/45] loss=0.5139 val_acc=1.0000 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 010/45] loss=0.4852 val_acc=1.0000 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 011/45] loss=0.4926 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 012/45] loss=0.4738 val_acc=1.0000 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 013/45] loss=0.4582 val_acc=1.0000 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 014/45] loss=0.4216 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 015/45] loss=0.4032 val_acc=1.0000 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 016/45] loss=0.3912 val_acc=1.0000 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 017/45] loss=0.3874 val_acc=1.0000 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 018/45] loss=0.3229 val_acc=1.0000 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 019/45] loss=0.3255 val_acc=1.0000 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 020/45] loss=0.3801 val_acc=1.0000 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 021/45] loss=0.3920 val_acc=1.0000 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 022/45] loss=0.3017 val_acc=1.0000 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 023/45] loss=0.3035 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 024/45] loss=0.2574 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 025/45] loss=0.2420 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 026/45] loss=0.2158 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 027/45] loss=0.2534 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 028/45] loss=0.2027 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 029/45] loss=0.2129 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 030/45] loss=0.2003 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 031/45] loss=0.2117 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 032/45] loss=0.1917 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 033/45] loss=0.2177 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 034/45] loss=0.1842 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 035/45] loss=0.1388 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 036/45] loss=0.0839 val_acc=1.0000 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 037/45] loss=0.0570 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 038/45] loss=0.0606 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 039/45] loss=0.0448 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 040/45] loss=0.0447 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 041/45] loss=0.0330 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 042/45] loss=0.0321 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 043/45] loss=0.0328 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 044/45] loss=0.0321 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
[Epoch 045/45] loss=0.0310 val_acc=0.9898 val_auroc=1.0000 best(accuracy)=1.0000
  binarizer mode=quantize | early_stop=accuracy

========================================================================
hyconex/blobs | train (959, 2) | classes 3
========================================================================
  Strategie: TabResNet instance (HybridDRNetModel)
[Epoch 001/45] [warmup] loss=0.4306 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9500
[Epoch 002/45] [warmup] loss=0.0945 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9500
[Epoch 003/45] loss=0.3726 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9500
[Epoch 004/45] loss=0.2211 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9500
[Epoch 005/45] loss=0.2027 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9500
[Epoch 006/45] loss=0.1898 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9500
[Epoch 007/45] loss=0.1771 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 008/45] loss=0.1672 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 009/45] loss=0.1663 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 010/45] loss=0.1770 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 011/45] loss=0.1765 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 012/45] loss=0.1694 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 013/45] loss=0.1862 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 014/45] loss=0.1907 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 015/45] loss=0.1815 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 016/45] loss=0.1767 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 017/45] loss=0.1756 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 018/45] loss=0.1674 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 019/45] loss=0.1650 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 020/45] loss=0.1635 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 021/45] loss=0.1686 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 022/45] loss=0.1725 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 023/45] loss=0.1678 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 024/45] loss=0.1656 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 025/45] loss=0.1603 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 026/45] loss=0.1590 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 027/45] loss=0.1579 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 028/45] loss=0.1587 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 029/45] loss=0.1661 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 030/45] loss=0.1674 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 031/45] loss=0.1613 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 032/45] loss=0.1571 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 033/45] loss=0.1553 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 034/45] loss=0.1551 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 035/45] loss=0.1553 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 036/45] loss=0.1590 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 037/45] loss=0.1558 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 038/45] loss=0.1561 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 039/45] loss=0.1553 val_acc=0.9708 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 040/45] loss=0.1544 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 041/45] loss=0.1554 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 042/45] loss=0.1542 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 043/45] loss=0.1552 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 044/45] loss=0.1544 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
[Epoch 045/45] loss=0.1585 val_acc=0.9500 val_auroc=0.9978 best(accuracy)=0.9708
  binarizer mode=quantize | early_stop=accuracy

========================================================================
hyconex/compas | train (2693, 25) | classes 3
========================================================================
  Strategie: TabResNet instance (HybridDRNetModel)

D:\ecole\master 2\recherche\INN\projet\HyConEx\counterfactuals\datasets\compas.py:43: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  raw_data["length_of_stay"].fillna(
D:\ecole\master 2\recherche\INN\projet\HyConEx\counterfactuals\datasets\compas.py:46: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  raw_data["days_b_screening_arrest"].fillna(

[Epoch 001/45] [warmup] loss=1.1242 val_acc=0.5297 val_auroc=0.7490 best(accuracy)=0.5297
[Epoch 002/45] [warmup] loss=0.9160 val_acc=0.5356 val_auroc=0.7529 best(accuracy)=0.5356
[Epoch 003/45] loss=1.0960 val_acc=0.5415 val_auroc=0.7461 best(accuracy)=0.5415
[Epoch 004/45] loss=1.0569 val_acc=0.5401 val_auroc=0.7515 best(accuracy)=0.5415
[Epoch 005/45] loss=1.0407 val_acc=0.5341 val_auroc=0.7537 best(accuracy)=0.5415
[Epoch 006/45] loss=1.0261 val_acc=0.5490 val_auroc=0.7538 best(accuracy)=0.5490
[Epoch 007/45] loss=1.0204 val_acc=0.5534 val_auroc=0.7440 best(accuracy)=0.5534
[Epoch 008/45] loss=1.0110 val_acc=0.5371 val_auroc=0.7419 best(accuracy)=0.5534
[Epoch 009/45] loss=1.0058 val_acc=0.5460 val_auroc=0.7492 best(accuracy)=0.5534
[Epoch 010/45] loss=0.9870 val_acc=0.5341 val_auroc=0.7454 best(accuracy)=0.5534
[Epoch 011/45] loss=0.9942 val_acc=0.5475 val_auroc=0.7402 best(accuracy)=0.5534
[Epoch 012/45] loss=0.9844 val_acc=0.5638 val_auroc=0.7453 best(accuracy)=0.5638
[Epoch 013/45] loss=0.9755 val_acc=0.5653 val_auroc=0.7439 best(accuracy)=0.5653
[Epoch 014/45] loss=0.9825 val_acc=0.5549 val_auroc=0.7457 best(accuracy)=0.5653
[Epoch 015/45] loss=0.9743 val_acc=0.5445 val_auroc=0.7392 best(accuracy)=0.5653
[Epoch 016/45] loss=0.9588 val_acc=0.5579 val_auroc=0.7369 best(accuracy)=0.5653
[Epoch 017/45] loss=0.9608 val_acc=0.5386 val_auroc=0.7300 best(accuracy)=0.5653
[Epoch 018/45] loss=0.9668 val_acc=0.5682 val_auroc=0.7396 best(accuracy)=0.5682
[Epoch 019/45] loss=0.9465 val_acc=0.5519 val_auroc=0.7338 best(accuracy)=0.5682
[Epoch 020/45] loss=0.9497 val_acc=0.5475 val_auroc=0.7330 best(accuracy)=0.5682
[Epoch 021/45] loss=0.9386 val_acc=0.5401 val_auroc=0.7367 best(accuracy)=0.5682
[Epoch 022/45] loss=0.9444 val_acc=0.5549 val_auroc=0.7359 best(accuracy)=0.5682
[Epoch 023/45] loss=0.9339 val_acc=0.5549 val_auroc=0.7301 best(accuracy)=0.5682
[Epoch 024/45] loss=0.9601 val_acc=0.5564 val_auroc=0.7358 best(accuracy)=0.5682
[Epoch 025/45] loss=0.9347 val_acc=0.5386 val_auroc=0.7282 best(accuracy)=0.5682
[Epoch 026/45] loss=0.9272 val_acc=0.5430 val_auroc=0.7281 best(accuracy)=0.5682
[Epoch 027/45] loss=0.9273 val_acc=0.5326 val_auroc=0.7287 best(accuracy)=0.5682
[Epoch 028/45] loss=0.9263 val_acc=0.5490 val_auroc=0.7330 best(accuracy)=0.5682
[Epoch 029/45] loss=0.9319 val_acc=0.5371 val_auroc=0.7278 best(accuracy)=0.5682
[Epoch 030/45] loss=0.9220 val_acc=0.5564 val_auroc=0.7315 best(accuracy)=0.5682
[Epoch 031/45] loss=0.9159 val_acc=0.5415 val_auroc=0.7277 best(accuracy)=0.5682
[Epoch 032/45] loss=0.9181 val_acc=0.5371 val_auroc=0.7274 best(accuracy)=0.5682
[Epoch 033/45] loss=0.9074 val_acc=0.5223 val_auroc=0.7291 best(accuracy)=0.5682
[Epoch 034/45] loss=0.9282 val_acc=0.5312 val_auroc=0.7215 best(accuracy)=0.5682
[Epoch 035/45] loss=0.9006 val_acc=0.5401 val_auroc=0.7270 best(accuracy)=0.5682
[Epoch 036/45] loss=0.9048 val_acc=0.5593 val_auroc=0.7232 best(accuracy)=0.5682
[Epoch 037/45] loss=0.8993 val_acc=0.5475 val_auroc=0.7308 best(accuracy)=0.5682
[Epoch 038/45] loss=0.8975 val_acc=0.5519 val_auroc=0.7236 best(accuracy)=0.5682
[Epoch 039/45] loss=0.9110 val_acc=0.5282 val_auroc=0.7227 best(accuracy)=0.5682
[Epoch 040/45] loss=0.9183 val_acc=0.5534 val_auroc=0.7261 best(accuracy)=0.5682
[Epoch 041/45] loss=0.9082 val_acc=0.5371 val_auroc=0.7245 best(accuracy)=0.5682
[Epoch 042/45] loss=0.9025 val_acc=0.5401 val_auroc=0.7240 best(accuracy)=0.5682
[Epoch 043/45] loss=0.8865 val_acc=0.5386 val_auroc=0.7163 best(accuracy)=0.5682
[Epoch 044/45] loss=0.8900 val_acc=0.5267 val_auroc=0.7236 best(accuracy)=0.5682
[Epoch 045/45] loss=0.8921 val_acc=0.5460 val_auroc=0.7114 best(accuracy)=0.5682
  binarizer mode=bipolar | early_stop=accuracy
Index(['default', 'account_check_status', 'duration_in_month',
       'credit_history', 'purpose', 'credit_amount', 'savings',
       'present_emp_since', 'installment_as_income_perc',
       'personal_status_sex', 'other_debtors', 'present_res_since', 'property',
       'age', 'other_installment_plans', 'housing', 'credits_this_bank', 'job',
       'people_under_maintenance', 'telephone', 'foreign_worker'],
      dtype='object')

========================================================================
hyconex/german_credit | train (384, 74) | classes 2
========================================================================
  Strategie: TabResNet instance (HybridDRNetModel)
[Epoch 001/45] [warmup] loss=1.4671 val_acc=0.5000 val_auroc=0.4900 best(accuracy)=0.5000
[Epoch 002/45] [warmup] loss=0.8047 val_acc=0.5000 val_auroc=0.5916 best(accuracy)=0.5000
[Epoch 003/45] loss=0.8725 val_acc=0.5000 val_auroc=0.6259 best(accuracy)=0.5000
[Epoch 004/45] loss=0.8712 val_acc=0.6562 val_auroc=0.6801 best(accuracy)=0.6562
[Epoch 005/45] loss=0.7928 val_acc=0.5833 val_auroc=0.6884 best(accuracy)=0.6562
[Epoch 006/45] loss=0.7253 val_acc=0.5312 val_auroc=0.7014 best(accuracy)=0.6562
[Epoch 007/45] loss=0.7722 val_acc=0.5938 val_auroc=0.6897 best(accuracy)=0.6562
[Epoch 008/45] loss=0.7347 val_acc=0.5938 val_auroc=0.6801 best(accuracy)=0.6562
[Epoch 009/45] loss=0.6741 val_acc=0.5625 val_auroc=0.6875 best(accuracy)=0.6562
[Epoch 010/45] loss=0.6571 val_acc=0.6250 val_auroc=0.6875 best(accuracy)=0.6562
[Epoch 011/45] loss=0.6554 val_acc=0.6146 val_auroc=0.6931 best(accuracy)=0.6562
[Epoch 012/45] loss=0.6566 val_acc=0.6146 val_auroc=0.7066 best(accuracy)=0.6562
[Epoch 013/45] loss=0.6101 val_acc=0.6146 val_auroc=0.6953 best(accuracy)=0.6562
[Epoch 014/45] loss=0.6124 val_acc=0.6458 val_auroc=0.6849 best(accuracy)=0.6562
[Epoch 015/45] loss=0.5886 val_acc=0.6250 val_auroc=0.6758 best(accuracy)=0.6562
[Epoch 016/45] loss=0.5642 val_acc=0.6042 val_auroc=0.6740 best(accuracy)=0.6562
[Epoch 017/45] loss=0.5589 val_acc=0.6146 val_auroc=0.6732 best(accuracy)=0.6562
[Epoch 018/45] loss=0.5653 val_acc=0.6042 val_auroc=0.6658 best(accuracy)=0.6562
[Epoch 019/45] loss=0.5414 val_acc=0.6146 val_auroc=0.6649 best(accuracy)=0.6562
[Epoch 020/45] loss=0.5213 val_acc=0.6250 val_auroc=0.6632 best(accuracy)=0.6562
[Epoch 021/45] loss=0.5108 val_acc=0.5938 val_auroc=0.6645 best(accuracy)=0.6562
[Epoch 022/45] loss=0.5176 val_acc=0.5625 val_auroc=0.6593 best(accuracy)=0.6562
[Epoch 023/45] loss=0.5154 val_acc=0.6250 val_auroc=0.6636 best(accuracy)=0.6562
[Epoch 024/45] loss=0.4936 val_acc=0.6146 val_auroc=0.6667 best(accuracy)=0.6562
[Epoch 025/45] loss=0.4877 val_acc=0.6042 val_auroc=0.6662 best(accuracy)=0.6562
[Epoch 026/45] loss=0.4870 val_acc=0.5938 val_auroc=0.6523 best(accuracy)=0.6562
[Epoch 027/45] loss=0.4840 val_acc=0.6250 val_auroc=0.6610 best(accuracy)=0.6562
[Epoch 028/45] loss=0.4897 val_acc=0.6146 val_auroc=0.6719 best(accuracy)=0.6562
[Epoch 029/45] loss=0.4842 val_acc=0.6042 val_auroc=0.6693 best(accuracy)=0.6562
[Epoch 030/45] loss=0.4806 val_acc=0.6042 val_auroc=0.6615 best(accuracy)=0.6562
[Epoch 031/45] loss=0.4832 val_acc=0.6042 val_auroc=0.6589 best(accuracy)=0.6562
[Epoch 032/45] loss=0.4844 val_acc=0.6250 val_auroc=0.6719 best(accuracy)=0.6562
[Epoch 033/45] loss=0.4860 val_acc=0.6042 val_auroc=0.6819 best(accuracy)=0.6562
[Epoch 034/45] loss=0.4871 val_acc=0.6042 val_auroc=0.6827 best(accuracy)=0.6562
[Epoch 035/45] loss=0.4843 val_acc=0.6042 val_auroc=0.6736 best(accuracy)=0.6562
[Epoch 036/45] loss=0.4792 val_acc=0.6042 val_auroc=0.6645 best(accuracy)=0.6562
[Epoch 037/45] loss=0.4809 val_acc=0.6146 val_auroc=0.6641 best(accuracy)=0.6562
[Epoch 038/45] loss=0.4808 val_acc=0.6146 val_auroc=0.6727 best(accuracy)=0.6562
[Epoch 039/45] loss=0.4807 val_acc=0.6250 val_auroc=0.6823 best(accuracy)=0.6562
[Epoch 040/45] loss=0.4832 val_acc=0.6458 val_auroc=0.6814 best(accuracy)=0.6562
[Epoch 041/45] loss=0.4799 val_acc=0.6250 val_auroc=0.6714 best(accuracy)=0.6562
[Epoch 042/45] loss=0.4791 val_acc=0.6042 val_auroc=0.6562 best(accuracy)=0.6562
[Epoch 043/45] loss=0.4849 val_acc=0.5833 val_auroc=0.6415 best(accuracy)=0.6562
[Epoch 044/45] loss=0.4725 val_acc=0.5833 val_auroc=0.6471 best(accuracy)=0.6562
[Epoch 045/45] loss=0.4789 val_acc=0.6042 val_auroc=0.6576 best(accuracy)=0.6562
  binarizer mode=bipolar | early_stop=accuracy

========================================================================
hyconex/heloc | train (6310, 23) | classes 2
========================================================================
  Strategie: TabResNet instance (HybridDRNetModel)
[Epoch 001/45] [warmup] loss=0.6033 val_acc=0.7009 val_auroc=0.7942 best(accuracy)=0.7009
[Epoch 002/45] [warmup] loss=0.5590 val_acc=0.6413 val_auroc=0.7933 best(accuracy)=0.7009
[Epoch 003/45] loss=0.7437 val_acc=0.7129 val_auroc=0.7973 best(accuracy)=0.7129
[Epoch 004/45] loss=0.7235 val_acc=0.7091 val_auroc=0.7922 best(accuracy)=0.7129
[Epoch 005/45] loss=0.7209 val_acc=0.7079 val_auroc=0.7863 best(accuracy)=0.7129
[Epoch 006/45] loss=0.7146 val_acc=0.7123 val_auroc=0.7730 best(accuracy)=0.7129
[Epoch 007/45] loss=0.7042 val_acc=0.7079 val_auroc=0.7879 best(accuracy)=0.7129
[Epoch 008/45] loss=0.7032 val_acc=0.7212 val_auroc=0.7822 best(accuracy)=0.7212
[Epoch 009/45] loss=0.6880 val_acc=0.6774 val_auroc=0.7706 best(accuracy)=0.7212
[Epoch 010/45] loss=0.6848 val_acc=0.7041 val_auroc=0.7617 best(accuracy)=0.7212
[Epoch 011/45] loss=0.6714 val_acc=0.6990 val_auroc=0.7688 best(accuracy)=0.7212
[Epoch 012/45] loss=0.6669 val_acc=0.7167 val_auroc=0.7696 best(accuracy)=0.7212
[Epoch 013/45] loss=0.6560 val_acc=0.6800 val_auroc=0.7495 best(accuracy)=0.7212
[Epoch 014/45] loss=0.6440 val_acc=0.6958 val_auroc=0.7526 best(accuracy)=0.7212
[Epoch 015/45] loss=0.6359 val_acc=0.7110 val_auroc=0.7582 best(accuracy)=0.7212
[Epoch 016/45] loss=0.6333 val_acc=0.6850 val_auroc=0.7404 best(accuracy)=0.7212
[Epoch 017/45] loss=0.6239 val_acc=0.7047 val_auroc=0.7522 best(accuracy)=0.7212
[Epoch 018/45] loss=0.6110 val_acc=0.6958 val_auroc=0.7480 best(accuracy)=0.7212
[Epoch 019/45] loss=0.6128 val_acc=0.6876 val_auroc=0.7364 best(accuracy)=0.7212
[Epoch 020/45] loss=0.5674 val_acc=0.6971 val_auroc=0.7375 best(accuracy)=0.7212
[Epoch 021/45] loss=0.3574 val_acc=0.6869 val_auroc=0.7397 best(accuracy)=0.7212
[Epoch 022/45] loss=0.3603 val_acc=0.6705 val_auroc=0.7310 best(accuracy)=0.7212
[Epoch 023/45] loss=0.4971 val_acc=0.6831 val_auroc=0.7268 best(accuracy)=0.7212
[Epoch 024/45] loss=0.5825 val_acc=0.6907 val_auroc=0.7317 best(accuracy)=0.7212
[Epoch 025/45] loss=0.5728 val_acc=0.6578 val_auroc=0.7084 best(accuracy)=0.7212
[Epoch 026/45] loss=0.5248 val_acc=0.6705 val_auroc=0.7083 best(accuracy)=0.7212
[Epoch 027/45] loss=0.4695 val_acc=0.6755 val_auroc=0.7298 best(accuracy)=0.7212
[Epoch 028/45] loss=0.3854 val_acc=0.6705 val_auroc=0.7120 best(accuracy)=0.7212
[Epoch 029/45] loss=0.2582 val_acc=0.7022 val_auroc=0.7337 best(accuracy)=0.7212
[Epoch 030/45] loss=0.3146 val_acc=0.6749 val_auroc=0.7214 best(accuracy)=0.7212
[Epoch 031/45] loss=0.5530 val_acc=0.6717 val_auroc=0.7092 best(accuracy)=0.7212
[Epoch 032/45] loss=0.5483 val_acc=0.6844 val_auroc=0.7284 best(accuracy)=0.7212
[Epoch 033/45] loss=0.5407 val_acc=0.6692 val_auroc=0.7211 best(accuracy)=0.7212
[Epoch 034/45] loss=0.5227 val_acc=0.6793 val_auroc=0.7273 best(accuracy)=0.7212
[Epoch 035/45] loss=0.4111 val_acc=0.6901 val_auroc=0.7387 best(accuracy)=0.7212
[Epoch 036/45] loss=0.3845 val_acc=0.6616 val_auroc=0.7162 best(accuracy)=0.7212
[Epoch 037/45] loss=0.4207 val_acc=0.6812 val_auroc=0.7306 best(accuracy)=0.7212
[Epoch 038/45] loss=0.2793 val_acc=0.6717 val_auroc=0.7148 best(accuracy)=0.7212
[Epoch 039/45] loss=0.2660 val_acc=0.6876 val_auroc=0.7382 best(accuracy)=0.7212
[Epoch 040/45] loss=0.1967 val_acc=0.6882 val_auroc=0.7331 best(accuracy)=0.7212
[Epoch 041/45] loss=0.1944 val_acc=0.6755 val_auroc=0.7228 best(accuracy)=0.7212
[Epoch 042/45] loss=0.1810 val_acc=0.6705 val_auroc=0.7116 best(accuracy)=0.7212
[Epoch 043/45] loss=0.1556 val_acc=0.6838 val_auroc=0.7181 best(accuracy)=0.7212
[Epoch 044/45] loss=0.1497 val_acc=0.6869 val_auroc=0.7363 best(accuracy)=0.7212
[Epoch 045/45] loss=0.3108 val_acc=0.7079 val_auroc=0.7529 best(accuracy)=0.7212
  binarizer mode=quantize | early_stop=accuracy

========================================================================
hyconex/law | train (1420, 3) | classes 2
========================================================================
  Strategie: TabResNet instance (HybridDRNetModel)
[Epoch 001/45] [warmup] loss=0.6415 val_acc=0.6910 val_auroc=0.7811 best(accuracy)=0.6910
[Epoch 002/45] [warmup] loss=0.5212 val_acc=0.7219 val_auroc=0.7855 best(accuracy)=0.7219
[Epoch 003/45] loss=0.6951 val_acc=0.6882 val_auroc=0.7854 best(accuracy)=0.7219
[Epoch 004/45] loss=0.6284 val_acc=0.7135 val_auroc=0.7889 best(accuracy)=0.7219
[Epoch 005/45] loss=0.6110 val_acc=0.7163 val_auroc=0.7820 best(accuracy)=0.7219
[Epoch 006/45] loss=0.6066 val_acc=0.7107 val_auroc=0.7863 best(accuracy)=0.7219
[Epoch 007/45] loss=0.5883 val_acc=0.7135 val_auroc=0.7886 best(accuracy)=0.7219
[Epoch 008/45] loss=0.5908 val_acc=0.6994 val_auroc=0.7865 best(accuracy)=0.7219
[Epoch 009/45] loss=0.5720 val_acc=0.7191 val_auroc=0.7906 best(accuracy)=0.7219
[Epoch 010/45] loss=0.5817 val_acc=0.7135 val_auroc=0.7864 best(accuracy)=0.7219
[Epoch 011/45] loss=0.5884 val_acc=0.6994 val_auroc=0.7868 best(accuracy)=0.7219
[Epoch 012/45] loss=0.6245 val_acc=0.7163 val_auroc=0.7878 best(accuracy)=0.7219
[Epoch 013/45] loss=0.5966 val_acc=0.7135 val_auroc=0.7916 best(accuracy)=0.7219
[Epoch 014/45] loss=0.6080 val_acc=0.7163 val_auroc=0.7905 best(accuracy)=0.7219
[Epoch 015/45] loss=0.5828 val_acc=0.7135 val_auroc=0.7898 best(accuracy)=0.7219
[Epoch 016/45] loss=0.6146 val_acc=0.7135 val_auroc=0.7832 best(accuracy)=0.7219
[Epoch 017/45] loss=0.6024 val_acc=0.7079 val_auroc=0.7835 best(accuracy)=0.7219
[Epoch 018/45] loss=0.5705 val_acc=0.7022 val_auroc=0.7891 best(accuracy)=0.7219
[Epoch 019/45] loss=0.5874 val_acc=0.7079 val_auroc=0.7868 best(accuracy)=0.7219
[Epoch 020/45] loss=0.5843 val_acc=0.6966 val_auroc=0.7835 best(accuracy)=0.7219
[Epoch 021/45] loss=0.5675 val_acc=0.7163 val_auroc=0.7940 best(accuracy)=0.7219
[Epoch 022/45] loss=0.5682 val_acc=0.7051 val_auroc=0.7913 best(accuracy)=0.7219
[Epoch 023/45] loss=0.5995 val_acc=0.7163 val_auroc=0.7877 best(accuracy)=0.7219
[Epoch 024/45] loss=0.5717 val_acc=0.7163 val_auroc=0.7895 best(accuracy)=0.7219
[Epoch 025/45] loss=0.5740 val_acc=0.7051 val_auroc=0.7919 best(accuracy)=0.7219
[Epoch 026/45] loss=0.5949 val_acc=0.7135 val_auroc=0.7926 best(accuracy)=0.7219
[Epoch 027/45] loss=0.5668 val_acc=0.7079 val_auroc=0.7924 best(accuracy)=0.7219
[Epoch 028/45] loss=0.5642 val_acc=0.7107 val_auroc=0.7931 best(accuracy)=0.7219
[Epoch 029/45] loss=0.5629 val_acc=0.7051 val_auroc=0.7905 best(accuracy)=0.7219
[Epoch 030/45] loss=0.5717 val_acc=0.7107 val_auroc=0.7933 best(accuracy)=0.7219
[Epoch 031/45] loss=0.5769 val_acc=0.7079 val_auroc=0.7875 best(accuracy)=0.7219
[Epoch 032/45] loss=0.5586 val_acc=0.7022 val_auroc=0.7932 best(accuracy)=0.7219
[Epoch 033/45] loss=0.5854 val_acc=0.7163 val_auroc=0.7938 best(accuracy)=0.7219
[Epoch 034/45] loss=0.5606 val_acc=0.7135 val_auroc=0.7935 best(accuracy)=0.7219
[Epoch 035/45] loss=0.5576 val_acc=0.7107 val_auroc=0.7915 best(accuracy)=0.7219
[Epoch 036/45] loss=0.5588 val_acc=0.7107 val_auroc=0.7901 best(accuracy)=0.7219
[Epoch 037/45] loss=0.5593 val_acc=0.7107 val_auroc=0.7862 best(accuracy)=0.7219
[Epoch 038/45] loss=0.5597 val_acc=0.7051 val_auroc=0.7872 best(accuracy)=0.7219
[Epoch 039/45] loss=0.5621 val_acc=0.7135 val_auroc=0.7877 best(accuracy)=0.7219
[Epoch 040/45] loss=0.5600 val_acc=0.7135 val_auroc=0.7882 best(accuracy)=0.7219
[Epoch 041/45] loss=0.5606 val_acc=0.7051 val_auroc=0.7888 best(accuracy)=0.7219
[Epoch 042/45] loss=0.5592 val_acc=0.7051 val_auroc=0.7897 best(accuracy)=0.7219
[Epoch 043/45] loss=0.5818 val_acc=0.7079 val_auroc=0.7889 best(accuracy)=0.7219
[Epoch 044/45] loss=0.5744 val_acc=0.7022 val_auroc=0.7869 best(accuracy)=0.7219
[Epoch 045/45] loss=0.5640 val_acc=0.7135 val_auroc=0.7880 best(accuracy)=0.7219
  binarizer mode=quantize | early_stop=accuracy

========================================================================
hyconex/moons | train (654, 2) | classes 2
========================================================================
  Strategie: TabResNet instance (HybridDRNetModel)
[Epoch 001/45] [warmup] loss=0.4224 val_acc=0.9573 val_auroc=0.9817 best(accuracy)=0.9573
[Epoch 002/45] [warmup] loss=0.1230 val_acc=0.8537 val_auroc=0.9816 best(accuracy)=0.9573
[Epoch 003/45] loss=0.4473 val_acc=0.9573 val_auroc=0.9877 best(accuracy)=0.9573
[Epoch 004/45] loss=0.2204 val_acc=0.9512 val_auroc=0.9761 best(accuracy)=0.9573
[Epoch 005/45] loss=0.2449 val_acc=0.9085 val_auroc=0.9884 best(accuracy)=0.9573
[Epoch 006/45] loss=0.2202 val_acc=0.9329 val_auroc=0.9717 best(accuracy)=0.9573
[Epoch 007/45] loss=0.1844 val_acc=0.9573 val_auroc=0.9888 best(accuracy)=0.9573
[Epoch 008/45] loss=0.1703 val_acc=0.9573 val_auroc=0.9865 best(accuracy)=0.9573
[Epoch 009/45] loss=0.1617 val_acc=0.9573 val_auroc=0.9885 best(accuracy)=0.9573
[Epoch 010/45] loss=0.1507 val_acc=0.9573 val_auroc=0.9883 best(accuracy)=0.9573
[Epoch 011/45] loss=0.1506 val_acc=0.9573 val_auroc=0.9868 best(accuracy)=0.9573
[Epoch 012/45] loss=0.1553 val_acc=0.9573 val_auroc=0.9859 best(accuracy)=0.9573
[Epoch 013/45] loss=0.1486 val_acc=0.9573 val_auroc=0.9877 best(accuracy)=0.9573
[Epoch 014/45] loss=0.1550 val_acc=0.9573 val_auroc=0.9869 best(accuracy)=0.9573
[Epoch 015/45] loss=0.1493 val_acc=0.9573 val_auroc=0.9854 best(accuracy)=0.9573
[Epoch 016/45] loss=0.1591 val_acc=0.9573 val_auroc=0.9848 best(accuracy)=0.9573
[Epoch 017/45] loss=0.1448 val_acc=0.9573 val_auroc=0.9830 best(accuracy)=0.9573
[Epoch 018/45] loss=0.1470 val_acc=0.9573 val_auroc=0.9872 best(accuracy)=0.9573
[Epoch 019/45] loss=0.1436 val_acc=0.9634 val_auroc=0.9874 best(accuracy)=0.9634
[Epoch 020/45] loss=0.1454 val_acc=0.9634 val_auroc=0.9885 best(accuracy)=0.9634
[Epoch 021/45] loss=0.1425 val_acc=0.9573 val_auroc=0.9871 best(accuracy)=0.9634
[Epoch 022/45] loss=0.1396 val_acc=0.9573 val_auroc=0.9877 best(accuracy)=0.9634
[Epoch 023/45] loss=0.1444 val_acc=0.9634 val_auroc=0.9877 best(accuracy)=0.9634
[Epoch 024/45] loss=0.1453 val_acc=0.9573 val_auroc=0.9869 best(accuracy)=0.9634
[Epoch 025/45] loss=0.1469 val_acc=0.9573 val_auroc=0.9880 best(accuracy)=0.9634
[Epoch 026/45] loss=0.1425 val_acc=0.9573 val_auroc=0.9883 best(accuracy)=0.9634
[Epoch 027/45] loss=0.1408 val_acc=0.9634 val_auroc=0.9883 best(accuracy)=0.9634
[Epoch 028/45] loss=0.1424 val_acc=0.9573 val_auroc=0.9877 best(accuracy)=0.9634
[Epoch 029/45] loss=0.1422 val_acc=0.9573 val_auroc=0.9874 best(accuracy)=0.9634
[Epoch 030/45] loss=0.1408 val_acc=0.9512 val_auroc=0.9865 best(accuracy)=0.9634
[Epoch 031/45] loss=0.1504 val_acc=0.9512 val_auroc=0.9833 best(accuracy)=0.9634
[Epoch 032/45] loss=0.1413 val_acc=0.9512 val_auroc=0.9808 best(accuracy)=0.9634
[Epoch 033/45] loss=0.1383 val_acc=0.9512 val_auroc=0.9808 best(accuracy)=0.9634
[Epoch 034/45] loss=0.1455 val_acc=0.9512 val_auroc=0.9814 best(accuracy)=0.9634
[Epoch 035/45] loss=0.1406 val_acc=0.9512 val_auroc=0.9820 best(accuracy)=0.9634
[Epoch 036/45] loss=0.1436 val_acc=0.9512 val_auroc=0.9820 best(accuracy)=0.9634
[Epoch 037/45] loss=0.1426 val_acc=0.9512 val_auroc=0.9820 best(accuracy)=0.9634
[Epoch 038/45] loss=0.1387 val_acc=0.9512 val_auroc=0.9783 best(accuracy)=0.9634
[Epoch 039/45] loss=0.1406 val_acc=0.9512 val_auroc=0.9780 best(accuracy)=0.9634
[Epoch 040/45] loss=0.1393 val_acc=0.9512 val_auroc=0.9783 best(accuracy)=0.9634
[Epoch 041/45] loss=0.1437 val_acc=0.9512 val_auroc=0.9825 best(accuracy)=0.9634
[Epoch 042/45] loss=0.1346 val_acc=0.9512 val_auroc=0.9820 best(accuracy)=0.9634
[Epoch 043/45] loss=0.1349 val_acc=0.9512 val_auroc=0.9820 best(accuracy)=0.9634
[Epoch 044/45] loss=0.1384 val_acc=0.9512 val_auroc=0.9820 best(accuracy)=0.9634
[Epoch 045/45] loss=0.1350 val_acc=0.9512 val_auroc=0.9820 best(accuracy)=0.9634
  binarizer mode=quantize | early_stop=accuracy


,dataset,mode,best_val_acc,best_val_auroc,test_acc,test_auroc,cf_validity,cf_changed_bits,cf_l1,n_rules
0,hyconex/adult,instance,0.8259,0.8812,0.8231,0.8846,0.7593,15.5417,15.5417,44
1,hyconex/audit,instance,1.0000,1.0000,1.0000,1.0000,0.0000,24.3689,2.4675,44
2,hyconex/blobs,instance,0.9708,0.9978,0.9433,0.9974,0.6267,3.5867,0.7693,50
3,hyconex/compas,instance,0.5682,0.7396,0.5368,0.7102,0.4703,13.6859,13.6859,50
4,hyconex/german_credit,instance,0.6562,0.6801,0.6917,0.7689,0.3083,38.4000,37.6667,44
5,hyconex/heloc,instance,0.7212,0.7822,0.7182,0.7833,0.2818,37.9356,5.0773,44
6,hyconex/law,instance,0.7219,0.7855,0.7590,0.8557,0.2500,6.4437,0.7899,44
7,hyconex/moons,instance,0.9634,0.9874,0.9805,0.9850,0.9805,4.5756,0.4684,44
8,hyconex/moons_with_blob,instance,0.8938,0.9398,0.8800,0.9360,0.3700,4.0550,0.4142,44
9,hyperlogic/brca-n,instance,0.5000,0.5000,0.4889,0.5000,0.5111,64.9556,0.0000,44
10,hyperlogic/brca-s,instance,0.2667,0.5000,0.2632,0.5000,0.2456,62.2456,0.0000,56
11,hyperlogic/cardio,instance,0.7256,0.7895,0.7201,0.7897,0.7057,17.1671,17.1671,44
12,hyperlogic/disease,instance,1.0000,1.0000,1.0000,1.0000,0.0000,69.6976,68.5238,128

Échecs:
- hyconex/wine : list index out of range

## Helpers contrefactuels et règles

In [ ]:
def build_cf_table_instance(run: dict, n_examples: int = 3, seed: int = 42) -> pd.DataFrame:
    trainer = run['trainer']
    splits = run['splits']
    model = trainer.model
    assert model is not None

    x_test_bin = trainer.binarizer.transform(splits.X_test)
    x_test_t = torch.tensor(x_test_bin, dtype=torch.float32, device=trainer.device)
    with torch.no_grad():
        y_pred = torch.argmax(model.predict_logits(x_test_t), dim=1).cpu().numpy()

    pool = np.where(y_pred == splits.y_test)[0]
    rng = np.random.default_rng(seed)
    n = min(n_examples, len(pool))
    idx = rng.choice(pool, size=n, replace=False) if n > 0 else np.array([], dtype=int)
    if idx.size == 0:
        return pd.DataFrame()

    x_sub = torch.tensor(x_test_bin[idx], dtype=torch.float32, device=trainer.device)
    y_pred_orig = torch.tensor(y_pred[idx], dtype=torch.long, device=trainer.device)
    bin_names = trainer.binarizer.binary_feature_names()
    class_names = splits.class_names

    with torch.no_grad():
        x_cf_all, logits_cf_all = model.generate_counterfactuals_all_classes(x_sub, y_pred_orig)
        y_pred_cf = torch.argmax(logits_cf_all, dim=2).cpu().numpy()

    x_sub_np = x_sub.cpu().numpy()
    x_cf_np = x_cf_all.cpu().numpy()
    rows = []
    for i, sample_idx in enumerate(idx):
        src = int(y_pred_orig[i].item())
        for target in range(len(class_names)):
            if target == src:
                continue
            x_cf = x_cf_np[i, target]
            diff = np.where(np.abs(x_sub_np[i] - x_cf) > 1e-6)[0]
            flips = [f"{bin_names[j]}: {int(x_sub_np[i,j])}→{int(x_cf[j])}" for j in diff[:6]]
            if len(diff) > 6:
                flips.append(f"…+{len(diff)-6}")
            rows.append({
                'sample': int(sample_idx),
                'pred': class_names[src],
                'target': class_names[target],
                'valid_cf': int(y_pred_cf[i, target] == target),
                'n_flips': len(diff),
                'flips': '; '.join(flips),
            })
    return pd.DataFrame(rows)


def build_cf_table_bipolar(run: dict, n_examples: int = 3, seed: int = 42) -> pd.DataFrame:
    trainer = run['trainer']
    splits = run['splits']
    assert trainer._bipolar is not None

    x_test = np.asarray(splits.X_test, dtype=np.float32)
    x_bin = continuous_to_bipolar(x_test)
    with torch.no_grad():
        x_t = torch.tensor(x_bin, dtype=torch.float32, device=trainer.device)
        y_pred = trainer.model(x_t).argmax(dim=1).cpu().numpy()

    pool = np.where(y_pred == splits.y_test)[0]
    rng = np.random.default_rng(seed)
    n = min(n_examples, len(pool))
    idx = rng.choice(pool, size=n, replace=False) if n > 0 else np.array([], dtype=int)
    if idx.size == 0:
        return pd.DataFrame()

    rows = []
    for sample_idx in idx:
        src = int(y_pred[sample_idx])
        for target in range(len(splits.class_names)):
            if target == src:
                continue
            cf = explain_counterfactual_bipolar(
                trainer._bipolar,
                x_bin,
                int(sample_idx),
                target,
                feature_names=splits.feature_names,
                class_names=splits.class_names,
                y_true=int(splits.y_test[sample_idx]),
            )
            cf['sample'] = int(sample_idx)
            cf['pred'] = splits.class_names[src]
            cf['target'] = splits.class_names[target]
            cf['valid_cf'] = int(cf['valid'])
            cf['flips'] = '; '.join(
                f"{f['feature']}: {f['from']}→{f['to']}" for f in cf.get('flips', [])
            )
            rows.append({k: cf[k] for k in ('sample', 'pred', 'target', 'valid_cf', 'n_flips', 'flips')})
    return pd.DataFrame(rows)


def build_cf_table(run: dict, **kwargs) -> pd.DataFrame:
    if run['result'].mode == 'bipolar_hyper':
        return build_cf_table_bipolar(run, **kwargs)
    return build_cf_table_instance(run, **kwargs)


def rules_dataframe(run: dict, top_n: int = 10) -> pd.DataFrame:
    df = pd.DataFrame(run['rules'][:top_n])
    if 'if' in df.columns:
        df['if'] = df['if'].apply(lambda conds: ' AND\n'.join(conds) if isinstance(conds, list) else conds)
    return df

## Par jeu : contrefactuels et règles

In [6]:
for ds_key, run in runs.items():
    mode = run['result'].mode
    display(Markdown(f"### `{ds_key}` — mode `{mode}` — contrefactuels"))
    cf_df = build_cf_table(run, n_examples=3)
    with pd.option_context('display.max_colwidth', 120, 'display.max_rows', 24):
        display(cf_df)

    display(Markdown(f"### `{ds_key}` — règles (top 10)"))
    with pd.option_context('display.max_colwidth', None, 'display.max_rows', None):
        display(rules_dataframe(run, top_n=10))

### `hyconex/adult` — mode `instance` — contrefactuels

,sample,pred,target,valid_cf,n_flips,flips
0,4233,0,1,1,17,"age_bin0_[0.000,0.151): 1→-1; age_bin1_[0.151,0.274): -1→1; age_bin2_[0.274,0.411): -1→1; age_bin3_[0.411,1.000): -1..."
1,592,0,1,1,19,"age_bin0_[0.000,0.151): 1→-1; age_bin1_[0.151,0.274): -1→1; age_bin2_[0.274,0.411): -1→1; age_bin3_[0.411,1.000): -1..."
2,5013,0,1,1,15,"age_bin1_[0.151,0.274): -1→1; age_bin3_[0.411,1.000): -1→1; hours_per_week_bin0_[0.000,0.398): -1→1; workclass=Gover..."

### `hyconex/adult` — règles (top 10)

,rule_id,if,then_class,score
0,6,"education=School=-1 AND\nhours_per_week_bin2_[0.449,1.000)=-1 AND\nage_bin3_[0.411,1.000)=-1 AND\nage_bin2_[0.274,0.411)=-1",0,1.000000
1,18,"hours_per_week_bin1_[0.398,0.449)=-1 AND\nworkclass=Self-Employed=+1 AND\noccupation=Professional=-1 AND\nrace=Other=-1",0,1.000000
2,22,"workclass=Government=-1 AND\nworkclass=Self-Employed=-1 AND\nage_bin3_[0.411,1.000)=+1 AND\neducation=Assoc=+1",0,0.999999
3,43,"age_bin3_[0.411,1.000)=-1 AND\nmarital_status=Separated=-1 AND\nage_bin1_[0.151,0.274)=+1 AND\nworkclass=Private=+1",0,0.999998
4,17,"occupation=Professional=-1 AND\nworkclass=Self-Employed=-1 AND\nrace=Other=-1 AND\nhours_per_week_bin2_[0.449,1.000)=+1",0,0.999966
5,11,workclass=Self-Employed=+1 AND\nmarital_status=Widowed=-1 AND\nmarital_status=Single=+1 AND\noccupation=Other/Unknown=-1,0,0.999941
6,9,"hours_per_week_bin1_[0.398,0.449)=-1 AND\noccupation=White-Collar=-1 AND\nmarital_status=Single=+1 AND\nhours_per_week_bin0_[0.000,0.398)=+1",0,0.999662
7,31,"hours_per_week_bin2_[0.449,1.000)=+1 AND\nhours_per_week_bin0_[0.000,0.398)=-1 AND\neducation=Prof-school=-1 AND\nrace=White=+1",0,0.998466
8,38,"age_bin1_[0.151,0.274)=+1 AND\nrace=White=+1 AND\ngender=Male=+1 AND\neducation=Bachelors=-1",1,0.998421
9,0,"education=Assoc=-1 AND\nhours_per_week_bin1_[0.398,0.449)=+1 AND\nmarital_status=Separated=+1 AND\nrace=Other=-1",1,0.997381

### `hyconex/audit` — mode `instance` — contrefactuels

,sample,pred,target,valid_cf,n_flips,flips
0,79,0,1,0,20,"PARA_A_bin1_[0.004,0.013): 1→-1; PARA_A_bin2_[0.013,0.038): -1→1; Score_A_bin0_[0.000,0.500): 1→-1; Score_A_bin1_[0...."
1,10,0,1,0,18,"PARA_A_bin2_[0.013,0.038): -1→1; PARA_A_bin3_[0.038,1.000): -1→1; Score_A_bin0_[0.000,0.500): 1→-1; Score_A_bin1_[0...."
2,93,0,1,0,20,"PARA_A_bin1_[0.004,0.013): -1→1; Risk_A_bin0_[0.000,0.001): -1→1; PARA_B_bin0_[0.000,0.004): 1→-1; PARA_B_bin2_[0.04..."

### `hyconex/audit` — règles (top 10)

,rule_id,if,then_class,score
0,16,"Inherent_Risk_bin1_[0.000,0.003)=+1 AND\nAudit_Risk_bin3_[0.042,1.000)=-1 AND\nScore_A_bin0_[0.000,0.500)=-1 AND\nRisk_D_bin2_[0.011,1.000)=-1",0,0.986989
1,7,"Score_bin1_[0.125,0.500)=+1 AND\nRisk_C_bin0_[0.000,1.000)=+1 AND\nPARA_A_bin2_[0.013,0.038)=-1 AND\nScore_MV_bin0_[0.000,1.000)=+1",0,0.979324
2,26,"TOTAL_bin3_[0.078,1.000)=+1 AND\nMoney_Value_bin1_[0.000,0.011)=-1 AND\nRisk_F_bin0_[0.000,1.000)=+1 AND\nPARA_A_bin0_[0.000,0.004)=-1",0,0.966953
3,31,"Score_MV_bin0_[0.000,1.000)=-1 AND\nRisk_B_bin2_[0.040,1.000)=+1 AND\nInherent_Risk_bin1_[0.000,0.003)=-1 AND\nScore_bin2_[0.500,1.000)=+1",0,0.960627
4,14,"Risk_A_bin3_[0.038,1.000)=-1 AND\nProb_bin0_[0.000,1.000)=+1 AND\nMoney_Value_bin2_[0.011,1.000)=-1 AND\nAudit_Risk_bin3_[0.042,1.000)=-1",0,0.938886
5,17,"History_bin0_[0.000,1.000)=-1 AND\nRisk_B_bin2_[0.040,1.000)=+1 AND\nnumbers_bin0_[0.000,1.000)=-1 AND\nRisk_A_bin3_[0.038,1.000)=+1",1,0.920720
6,38,"TOTAL_bin1_[0.005,0.011)=+1 AND\nInherent_Risk_bin3_[0.032,1.000)=-1 AND\nRisk_F_bin0_[0.000,1.000)=-1 AND\nPARA_A_bin2_[0.013,0.038)=-1",0,0.908123
7,0,"numbers_bin0_[0.000,1.000)=-1 AND\nInherent_Risk_bin3_[0.032,1.000)=-1 AND\nProb_bin0_[0.000,1.000)=-1 AND\nRisk_F_bin0_[0.000,1.000)=+1",0,0.893957
8,18,"PROB_bin0_[0.000,1.000)=-1 AND\nPARA_A_bin3_[0.038,1.000)=-1 AND\nRisk_A_bin0_[0.000,0.001)=-1 AND\nRisk_D_bin1_[0.000,0.011)=-1",1,0.886130
9,42,"Risk_D_bin2_[0.011,1.000)=+1 AND\nRisk_A_bin2_[0.009,0.038)=-1 AND\nRisk_D_bin1_[0.000,0.011)=+1 AND\nProb_bin0_[0.000,1.000)=-1",0,0.881832

### `hyconex/blobs` — mode `instance` — contrefactuels

,sample,pred,target,valid_cf,n_flips,flips
0,197,1,0,1,4,"f0_bin0_[0.000,0.268): -1→1; f0_bin2_[0.442,0.754): -1→1; f0_bin3_[0.754,1.000): 1→-1; f1_bin0_[0.000,0.178): -1→1"
1,197,1,2,0,4,"f0_bin0_[0.000,0.268): -1→1; f0_bin2_[0.442,0.754): -1→1; f0_bin3_[0.754,1.000): 1→-1; f1_bin0_[0.000,0.178): -1→1"
2,26,0,1,1,4,"f0_bin0_[0.000,0.268): -1→1; f0_bin1_[0.268,0.442): -1→1; f1_bin0_[0.000,0.178): -1→1; f1_bin3_[0.728,1.000): 1→-1"
3,26,0,2,1,3,"f0_bin0_[0.000,0.268): -1→1; f1_bin0_[0.000,0.178): -1→1; f1_bin3_[0.728,1.000): 1→-1"
4,232,1,0,1,4,"f0_bin0_[0.000,0.268): -1→1; f0_bin2_[0.442,0.754): -1→1; f0_bin3_[0.754,1.000): 1→-1; f1_bin0_[0.000,0.178): -1→1"
5,232,1,2,0,4,"f0_bin0_[0.000,0.268): -1→1; f0_bin2_[0.442,0.754): -1→1; f0_bin3_[0.754,1.000): 1→-1; f1_bin0_[0.000,0.178): -1→1"

### `hyconex/blobs` — règles (top 10)

,rule_id,if,then_class,score
0,2,"f1_bin1_[0.178,0.491)=+1 AND\nf0_bin3_[0.754,1.000)=-1 AND\nf1_bin0_[0.000,0.178)=-1 AND\nf0_bin2_[0.442,0.754)=-1",2,0.999963
1,7,"f0_bin2_[0.442,0.754)=-1 AND\nf0_bin0_[0.000,0.268)=+1 AND\nf1_bin3_[0.728,1.000)=-1 AND\nf1_bin2_[0.491,0.728)=-1",2,0.999900
2,5,"f1_bin0_[0.000,0.178)=-1 AND\nf0_bin0_[0.000,0.268)=-1 AND\nf1_bin3_[0.728,1.000)=+1 AND\nf1_bin1_[0.178,0.491)=-1",0,0.999873
3,3,"f1_bin1_[0.178,0.491)=+1 AND\nf0_bin3_[0.754,1.000)=+1 AND\nf0_bin1_[0.268,0.442)=-1 AND\nf0_bin0_[0.000,0.268)=-1",1,0.999178
4,41,"f0_bin3_[0.754,1.000)=-1 AND\nf0_bin2_[0.442,0.754)=+1 AND\nf1_bin1_[0.178,0.491)=+1 AND\nf1_bin0_[0.000,0.178)=+1",1,0.999079
5,35,"f1_bin1_[0.178,0.491)=-1 AND\nf1_bin0_[0.000,0.178)=-1 AND\nf0_bin2_[0.442,0.754)=-1 AND\nf0_bin3_[0.754,1.000)=-1",0,0.998917
6,17,"f1_bin3_[0.728,1.000)=-1 AND\nf0_bin1_[0.268,0.442)=-1 AND\nf0_bin0_[0.000,0.268)=-1 AND\nf0_bin2_[0.442,0.754)=-1",1,0.995173
7,32,"f0_bin3_[0.754,1.000)=+1 AND\nf1_bin1_[0.178,0.491)=+1 AND\nf1_bin0_[0.000,0.178)=-1 AND\nf1_bin2_[0.491,0.728)=-1",1,0.989805
8,42,"f0_bin1_[0.268,0.442)=-1 AND\nf0_bin2_[0.442,0.754)=-1 AND\nf0_bin0_[0.000,0.268)=-1 AND\nf0_bin3_[0.754,1.000)=+1",1,0.989639
9,12,"f0_bin2_[0.442,0.754)=+1 AND\nf0_bin1_[0.268,0.442)=+1 AND\nf0_bin3_[0.754,1.000)=+1 AND\nf1_bin0_[0.000,0.178)=-1",0,0.988844

### `hyconex/compas` — mode `instance` — contrefactuels

,sample,pred,target,valid_cf,n_flips,flips
0,552,2,0,1,13,"age_bin2_[0.194,0.339): 1→-1; age_bin3_[0.339,1.000): -1→1; days_b_screening_arrest_bin0_[0.000,0.001): -1→1; length..."
1,552,2,1,0,13,"age_bin2_[0.194,0.339): 1→-1; age_bin3_[0.339,1.000): -1→1; days_b_screening_arrest_bin0_[0.000,0.001): -1→1; length..."
2,74,2,0,1,13,"age_bin1_[0.097,0.194): 1→-1; age_bin3_[0.339,1.000): -1→1; days_b_screening_arrest_bin0_[0.000,0.001): -1→1; length..."
3,74,2,1,0,13,"age_bin1_[0.097,0.194): 1→-1; age_bin3_[0.339,1.000): -1→1; days_b_screening_arrest_bin0_[0.000,0.001): -1→1; length..."
4,662,0,1,0,11,"priors_count_bin0_[0.000,0.053): 1→-1; priors_count_bin2_[0.158,1.000): -1→1; days_b_screening_arrest_bin0_[0.000,0...."
5,662,0,2,1,11,"priors_count_bin0_[0.000,0.053): 1→-1; priors_count_bin2_[0.158,1.000): -1→1; days_b_screening_arrest_bin0_[0.000,0...."

### `hyconex/compas` — règles (top 10)

,rule_id,if,then_class,score
0,5,"days_b_screening_arrest_bin0_[0.000,0.001)=+1 AND\nrace=Hispanic=+1 AND\nc_charge_degree=F=+1 AND\nis_violent_recid_bin0_[0.000,1.000)=-1",0,0.979008
1,0,"two_year_recid_bin0_[0.000,1.000)=+1 AND\nage_bin0_[0.000,0.097)=+1 AND\npriors_count_bin2_[0.158,1.000)=+1 AND\nage_bin2_[0.194,0.339)=-1",2,0.967936
2,8,"race=Hispanic=-1 AND\nc_charge_degree=F=-1 AND\nlength_of_stay_bin1_[0.001,0.016)=+1 AND\nage_bin1_[0.097,0.194)=-1",1,0.933386
3,49,"race=Other=+1 AND\nis_violent_recid_bin0_[0.000,1.000)=+1 AND\nlength_of_stay_bin1_[0.001,0.016)=-1 AND\npriors_count_bin0_[0.000,0.053)=+1",0,0.905750
4,44,"priors_count_bin0_[0.000,0.053)=-1 AND\npriors_count_bin2_[0.158,1.000)=+1 AND\nrace=Hispanic=+1 AND\nage_bin2_[0.194,0.339)=-1",0,0.889194
5,24,"is_recid_bin0_[0.000,1.000)=+1 AND\nage_bin2_[0.194,0.339)=+1 AND\npriors_count_bin2_[0.158,1.000)=-1 AND\nc_charge_degree=M=-1",2,0.858934
6,1,"race=Asian=-1 AND\nc_charge_degree=M=-1 AND\ntwo_year_recid_bin0_[0.000,1.000)=+1 AND\nsex=Male=+1",1,0.842804
7,32,"age_bin2_[0.194,0.339)=+1 AND\nrace=Other=+1 AND\nis_recid_bin0_[0.000,1.000)=-1 AND\nc_charge_degree=F=-1",2,0.834131
8,29,"race=Hispanic=+1 AND\nlength_of_stay_bin0_[0.000,0.001)=-1 AND\nis_violent_recid_bin0_[0.000,1.000)=-1 AND\ndays_b_screening_arrest_bin1_[0.001,1.000)=+1",1,0.832473
9,39,"length_of_stay_bin1_[0.001,0.016)=+1 AND\nis_violent_recid_bin0_[0.000,1.000)=+1 AND\nage_bin1_[0.097,0.194)=-1 AND\nrace=Caucasian=+1",0,0.830937

### `hyconex/german_credit` — mode `instance` — contrefactuels

,sample,pred,target,valid_cf,n_flips,flips
0,73,1,0,0,43,"duration_in_month_bin1_[0.118,0.250): -1→1; duration_in_month_bin2_[0.250,0.382): 1→-1; duration_in_month_bin3_[0.38..."
1,12,0,1,0,38,"duration_in_month_bin1_[0.118,0.250): -1→1; duration_in_month_bin2_[0.250,0.382): -1→1; duration_in_month_bin3_[0.38..."
2,89,1,0,0,33,"duration_in_month_bin1_[0.118,0.250): -1→1; duration_in_month_bin3_[0.382,1.000): 1→-1; installment_as_income_perc_b..."

### `hyconex/german_credit` — règles (top 10)

,rule_id,if,then_class,score
0,8,"purpose=car (new)=+1 AND\ncredit_history=critical account/ other credits existing (not at this bank)=+1 AND\nproperty=if not A121/A122 : car or other, not in attribute 6=-1 AND\nduration_in_month_bin1_[0.118,0.250)=-1",0,0.976138
1,7,"purpose=education=+1 AND\npresent_emp_since=... < 1 year =+1 AND\nsavings=100 <= ... < 500 DM=+1 AND\ninstallment_as_income_perc_bin2_[0.667,1.000)=-1",1,0.965162
2,13,"purpose=car (new)=+1 AND\njob=management/ self-employed/ highly qualified employee/ officer=+1 AND\nother_installment_plans=bank=-1 AND\nduration_in_month_bin1_[0.118,0.250)=+1",1,0.958454
3,25,"credits_this_bank_bin0_[0.000,0.333)=-1 AND\nage_bin2_[0.222,0.389)=-1 AND\ncredits_this_bank_bin1_[0.333,1.000)=+1 AND\naccount_check_status=0 <= ... < 200 DM=+1",1,0.954825
4,33,"credit_history=critical account/ other credits existing (not at this bank)=-1 AND\nage_bin0_[0.000,0.111)=-1 AND\nsavings=... < 100 DM=+1 AND\ncredit_amount_bin1_[0.067,0.134)=-1",0,0.940771
5,19,"other_installment_plans=stores=+1 AND\naccount_check_status=>= 200 DM / salary assignments for at least 1 year=+1 AND\ninstallment_as_income_perc_bin2_[0.667,1.000)=+1 AND\ncredit_amount_bin0_[0.000,0.067)=-1",0,0.918909
6,21,savings=100 <= ... < 500 DM=+1 AND\npurpose=furniture/equipment=-1 AND\npurpose=business=-1 AND\njob=unemployed/ unskilled - non-resident=-1,0,0.911086
7,23,"present_emp_since=... < 1 year =+1 AND\npresent_emp_since=unemployed=-1 AND\nage_bin3_[0.389,1.000)=+1 AND\ncredit_amount_bin0_[0.000,0.067)=+1",0,0.899882
8,3,"property=unknown / no property=-1 AND\njob=skilled employee / official=+1 AND\npresent_res_since_bin1_[0.333,0.667)=-1 AND\npurpose=car (used)=-1",1,0.899417
9,35,"personal_status_sex=male : divorced/separated=-1 AND\nage_bin1_[0.111,0.222)=+1 AND\ncredit_amount_bin2_[0.134,0.285)=+1 AND\npersonal_status_sex=female : divorced/separated/married=+1",1,0.893797

### `hyconex/heloc` — mode `instance` — contrefactuels

,sample,pred,target,valid_cf,n_flips,flips
0,1271,Bad,Good,0,41,"ExternalRiskEstimate_bin0_[0.000,0.508): 1→-1; ExternalRiskEstimate_bin3_[0.770,1.000): -1→1; MSinceOldestTradeOpen_..."
1,174,Good,Bad,0,33,"MSinceOldestTradeOpen_bin2_[0.236,0.326): 1→-1; MSinceOldestTradeOpen_bin3_[0.326,1.000): -1→1; MSinceMostRecentTrad..."
2,1514,Bad,Good,0,43,"ExternalRiskEstimate_bin0_[0.000,0.508): 1→-1; ExternalRiskEstimate_bin3_[0.770,1.000): -1→1; MSinceOldestTradeOpen_..."

### `hyconex/heloc` — règles (top 10)

,rule_id,if,then_class,score
0,5,"NetFractionRevolvingBurden_bin1_[0.092,0.208)=+1 AND\nMSinceMostRecentTradeOpen_bin3_[0.053,1.000)=+1 AND\nMSinceMostRecentInqexcl7days_bin1_[0.250,0.281)=+1 AND\nPercentTradesWBalance_bin0_[0.000,0.537)=+1",Bad,0.999985
1,6,"NumInstallTradesWBalance_bin3_[0.407,1.000)=-1 AND\nMSinceOldestTradeOpen_bin3_[0.326,1.000)=-1 AND\nPercentInstallTrades_bin3_[0.450,1.000)=-1 AND\nMaxDelq2PublicRecLast12M_bin1_[0.556,0.667)=+1",Bad,0.999948
2,21,"MaxDelqEver_bin0_[0.000,0.667)=+1 AND\nNumInqLast6Mexcl7days_bin0_[0.000,0.015)=+1 AND\nPercentInstallTrades_bin1_[0.220,0.330)=-1 AND\nNumInqLast6M_bin0_[0.000,0.015)=+1",Bad,0.999686
3,10,"MaxDelqEver_bin1_[0.667,1.000)=+1 AND\nMSinceMostRecentDelq_bin1_[0.011,0.088)=+1 AND\nAverageMInFile_bin2_[0.226,0.289)=-1 AND\nMaxDelq2PublicRecLast12M_bin2_[0.667,0.778)=-1",Good,0.999610
4,18,"PercentInstallTrades_bin2_[0.330,0.450)=+1 AND\nPercentInstallTrades_bin3_[0.450,1.000)=+1 AND\nPercentTradesWBalance_bin3_[0.843,1.000)=-1 AND\nMSinceOldestTradeOpen_bin2_[0.236,0.326)=-1",Good,0.999531
5,17,"NumTrades90Ever2DerogPubRec_bin0_[0.000,1.000)=+1 AND\nNumInstallTradesWBalance_bin0_[0.000,0.333)=-1 AND\nNumInqLast6M_bin1_[0.015,0.030)=+1 AND\nMaxDelq2PublicRecLast12M_bin1_[0.556,0.667)=-1",Bad,0.999355
6,37,"PercentInstallTrades_bin0_[0.000,0.220)=-1 AND\nNumTotalTrades_bin1_[0.125,0.202)=-1 AND\nNumInqLast6Mexcl7days_bin2_[0.030,1.000)=+1 AND\nNetFractionInstallBurden_bin0_[0.000,0.125)=+1",Good,0.999138
7,40,"NumRevolvingTradesWBalance_bin2_[0.314,0.371)=+1 AND\nPercentTradesWBalance_bin1_[0.537,0.694)=-1 AND\nNumRevolvingTradesWBalance_bin3_[0.371,1.000)=-1 AND\nNetFractionRevolvingBurden_bin1_[0.092,0.208)=-1",Good,0.993415
8,24,"NumSatisfactoryTrades_bin0_[0.000,0.165)=-1 AND\nPercentTradesWBalance_bin0_[0.000,0.537)=+1 AND\nNumInqLast6Mexcl7days_bin0_[0.000,0.015)=-1 AND\nPercentTradesWBalance_bin3_[0.843,1.000)=+1",Bad,0.981887
9,7,"MSinceMostRecentDelq_bin1_[0.011,0.088)=-1 AND\nNumSatisfactoryTrades_bin3_[0.354,1.000)=+1 AND\nMSinceMostRecentTradeOpen_bin0_[0.000,0.013)=+1 AND\nPercentInstallTrades_bin3_[0.450,1.000)=+1",Good,0.975127

### `hyconex/law` — mode `instance` — contrefactuels

,sample,pred,target,valid_cf,n_flips,flips
0,278,1,0,0,4,"lsat_bin0_[0.000,0.463): -1→1; lsat_bin1_[0.463,0.612): -1→1; lsat_bin3_[0.731,1.000): 1→-1; gpa_bin3_[0.762,1.000):..."
1,37,0,1,0,7,"lsat_bin0_[0.000,0.463): -1→1; lsat_bin3_[0.731,1.000): -1→1; gpa_bin2_[0.619,0.762): 1→-1; gpa_bin3_[0.762,1.000): ..."
2,329,0,1,0,9,"lsat_bin1_[0.463,0.612): -1→1; lsat_bin2_[0.612,0.731): 1→-1; lsat_bin3_[0.731,1.000): -1→1; gpa_bin0_[0.000,0.476):..."

### `hyconex/law` — règles (top 10)

,rule_id,if,then_class,score
0,40,"zfygpa_bin1_[0.376,0.484)=+1 AND\ngpa_bin0_[0.000,0.476)=-1 AND\nlsat_bin0_[0.000,0.463)=+1 AND\nlsat_bin1_[0.463,0.612)=-1",1,0.991631
1,3,"gpa_bin1_[0.476,0.619)=+1 AND\nzfygpa_bin2_[0.484,0.607)=+1 AND\ngpa_bin0_[0.000,0.476)=-1 AND\nlsat_bin3_[0.731,1.000)=+1",1,0.989618
2,15,"lsat_bin3_[0.731,1.000)=+1 AND\nlsat_bin2_[0.612,0.731)=-1 AND\ngpa_bin0_[0.000,0.476)=+1 AND\ngpa_bin3_[0.762,1.000)=+1",1,0.971826
3,23,"gpa_bin1_[0.476,0.619)=-1 AND\nzfygpa_bin0_[0.000,0.376)=+1 AND\nzfygpa_bin2_[0.484,0.607)=-1 AND\nlsat_bin2_[0.612,0.731)=-1",0,0.960346
4,30,"zfygpa_bin0_[0.000,0.376)=-1 AND\nlsat_bin0_[0.000,0.463)=-1 AND\ngpa_bin3_[0.762,1.000)=-1 AND\ngpa_bin0_[0.000,0.476)=-1",1,0.952433
5,21,"lsat_bin0_[0.000,0.463)=+1 AND\nzfygpa_bin0_[0.000,0.376)=-1 AND\nzfygpa_bin2_[0.484,0.607)=-1 AND\nlsat_bin2_[0.612,0.731)=-1",1,0.938241
6,29,"gpa_bin3_[0.762,1.000)=-1 AND\ngpa_bin2_[0.619,0.762)=-1 AND\nlsat_bin0_[0.000,0.463)=+1 AND\nzfygpa_bin2_[0.484,0.607)=-1",1,0.931207
7,18,"zfygpa_bin1_[0.376,0.484)=-1 AND\nzfygpa_bin3_[0.607,1.000)=-1 AND\nlsat_bin1_[0.463,0.612)=-1 AND\nlsat_bin2_[0.612,0.731)=+1",0,0.920293
8,34,"lsat_bin0_[0.000,0.463)=+1 AND\nzfygpa_bin2_[0.484,0.607)=-1 AND\nlsat_bin2_[0.612,0.731)=+1 AND\ngpa_bin3_[0.762,1.000)=-1",1,0.916215
9,0,"gpa_bin3_[0.762,1.000)=+1 AND\ngpa_bin1_[0.476,0.619)=+1 AND\nlsat_bin0_[0.000,0.463)=+1 AND\nzfygpa_bin1_[0.376,0.484)=+1",0,0.876069

### `hyconex/moons` — mode `instance` — contrefactuels

,sample,pred,target,valid_cf,n_flips,flips
0,135,1.0,0.0,1,3,"f0_bin1_[0.337,0.498): -1→1; f1_bin2_[0.511,0.732): -1→1; f1_bin3_[0.732,1.000): -1→1"
1,17,1.0,0.0,1,3,"f0_bin3_[0.676,1.000): -1→1; f1_bin1_[0.289,0.511): -1→1; f1_bin3_[0.732,1.000): -1→1"
2,158,0.0,1.0,1,3,"f0_bin3_[0.676,1.000): -1→1; f1_bin1_[0.289,0.511): -1→1; f1_bin2_[0.511,0.732): -1→1"

### `hyconex/moons` — règles (top 10)

,rule_id,if,then_class,score
0,30,"f0_bin3_[0.676,1.000)=-1 AND\nf1_bin0_[0.000,0.289)=+1 AND\nf0_bin0_[0.000,0.337)=-1 AND\nf1_bin1_[0.289,0.511)=-1",1.0,0.999953
1,13,"f1_bin2_[0.511,0.732)=-1 AND\nf0_bin1_[0.337,0.498)=+1 AND\nf1_bin3_[0.732,1.000)=-1 AND\nf0_bin0_[0.000,0.337)=-1",1.0,0.999772
2,21,"f1_bin1_[0.289,0.511)=+1 AND\nf0_bin2_[0.498,0.676)=-1 AND\nf1_bin3_[0.732,1.000)=+1 AND\nf0_bin3_[0.676,1.000)=+1",1.0,0.999661
3,37,"f1_bin3_[0.732,1.000)=+1 AND\nf0_bin1_[0.337,0.498)=-1 AND\nf1_bin2_[0.511,0.732)=-1 AND\nf1_bin1_[0.289,0.511)=-1",0.0,0.999618
4,38,"f1_bin2_[0.511,0.732)=-1 AND\nf1_bin3_[0.732,1.000)=+1 AND\nf1_bin1_[0.289,0.511)=-1 AND\nf1_bin0_[0.000,0.289)=-1",0.0,0.999499
5,32,"f0_bin0_[0.000,0.337)=+1 AND\nf0_bin2_[0.498,0.676)=+1 AND\nf1_bin3_[0.732,1.000)=+1 AND\nf1_bin1_[0.289,0.511)=+1",1.0,0.998855
6,29,"f1_bin3_[0.732,1.000)=-1 AND\nf0_bin2_[0.498,0.676)=-1 AND\nf0_bin0_[0.000,0.337)=-1 AND\nf0_bin3_[0.676,1.000)=+1",1.0,0.998823
7,40,"f0_bin0_[0.000,0.337)=-1 AND\nf1_bin3_[0.732,1.000)=+1 AND\nf1_bin1_[0.289,0.511)=-1 AND\nf1_bin2_[0.511,0.732)=-1",0.0,0.998713
8,39,"f1_bin3_[0.732,1.000)=-1 AND\nf0_bin1_[0.337,0.498)=+1 AND\nf0_bin0_[0.000,0.337)=-1 AND\nf0_bin3_[0.676,1.000)=+1",1.0,0.998467
9,36,"f0_bin2_[0.498,0.676)=+1 AND\nf1_bin0_[0.000,0.289)=-1 AND\nf0_bin1_[0.337,0.498)=-1 AND\nf0_bin0_[0.000,0.337)=-1",0.0,0.998447

### `hyconex/moons_with_blob` — mode `instance` — contrefactuels

,sample,pred,target,valid_cf,n_flips,flips
0,134,0.0,1.0,0,2,"-0.15681690615571184_bin1_[0.297,0.382): 1→-1; -0.15681690615571184_bin2_[0.382,0.515): -1→1"
1,17,0.0,1.0,0,3,"-0.15681690615571184_bin0_[0.000,0.297): 1→-1; -0.15681690615571184_bin1_[0.297,0.382): -1→1; -0.15681690615571184_b..."
2,156,1.0,0.0,1,6,"-0.15681690615571184_bin1_[0.297,0.382): -1→1; -0.15681690615571184_bin2_[0.382,0.515): -1→1; -0.15681690615571184_b..."

### `hyconex/moons_with_blob` — règles (top 10)

,rule_id,if,then_class,score
0,7,"0.31470276775106676_bin2_[0.438,0.516)=+1 AND\n0.31470276775106676_bin3_[0.516,1.000)=-1 AND\n0.31470276775106676_bin0_[0.000,0.171)=-1 AND\n0.31470276775106676_bin1_[0.171,0.438)=-1",0.0,0.996116
1,8,"0.31470276775106676_bin3_[0.516,1.000)=-1 AND\n-0.15681690615571184_bin2_[0.382,0.515)=+1 AND\n0.31470276775106676_bin0_[0.000,0.171)=-1 AND\n-0.15681690615571184_bin0_[0.000,0.297)=-1",0.0,0.994455
2,16,"0.31470276775106676_bin2_[0.438,0.516)=+1 AND\n0.31470276775106676_bin1_[0.171,0.438)=-1 AND\n0.31470276775106676_bin3_[0.516,1.000)=-1 AND\n-0.15681690615571184_bin2_[0.382,0.515)=+1",0.0,0.980824
3,28,"-0.15681690615571184_bin3_[0.515,1.000)=+1 AND\n-0.15681690615571184_bin0_[0.000,0.297)=+1 AND\n-0.15681690615571184_bin1_[0.297,0.382)=+1 AND\n0.31470276775106676_bin3_[0.516,1.000)=-1",1.0,0.975221
4,36,"-0.15681690615571184_bin3_[0.515,1.000)=+1 AND\n-0.15681690615571184_bin2_[0.382,0.515)=+1 AND\n-0.15681690615571184_bin0_[0.000,0.297)=-1 AND\n0.31470276775106676_bin2_[0.438,0.516)=+1",0.0,0.973325
5,31,"0.31470276775106676_bin0_[0.000,0.171)=+1 AND\n-0.15681690615571184_bin2_[0.382,0.515)=-1 AND\n-0.15681690615571184_bin1_[0.297,0.382)=+1 AND\n0.31470276775106676_bin3_[0.516,1.000)=-1",1.0,0.952885
6,13,"0.31470276775106676_bin0_[0.000,0.171)=+1 AND\n0.31470276775106676_bin1_[0.171,0.438)=+1 AND\n0.31470276775106676_bin2_[0.438,0.516)=+1 AND\n-0.15681690615571184_bin1_[0.297,0.382)=+1",1.0,0.932770
7,20,"0.31470276775106676_bin1_[0.171,0.438)=-1 AND\n0.31470276775106676_bin2_[0.438,0.516)=+1 AND\n-0.15681690615571184_bin2_[0.382,0.515)=-1 AND\n-0.15681690615571184_bin1_[0.297,0.382)=-1",0.0,0.924886
8,30,"-0.15681690615571184_bin1_[0.297,0.382)=-1 AND\n-0.15681690615571184_bin0_[0.000,0.297)=-1 AND\n0.31470276775106676_bin1_[0.171,0.438)=-1 AND\n0.31470276775106676_bin2_[0.438,0.516)=-1",1.0,0.902923
9,33,"-0.15681690615571184_bin3_[0.515,1.000)=-1 AND\n0.31470276775106676_bin2_[0.438,0.516)=+1 AND\n0.31470276775106676_bin0_[0.000,0.171)=+1 AND\n-0.15681690615571184_bin1_[0.297,0.382)=+1",1.0,0.902042

### `hyperlogic/brca-n` — mode `instance` — contrefactuels

,sample,pred,target,valid_cf,n_flips,flips
0,31,tumor,normal,0,67,"ENSG00000102048_bin0_[0.000,1.000): 1→-1; ENSG00000198963_bin0_[0.000,1.000): 1→-1; ENSG00000108684_bin0_[0.000,1.00..."
1,1,tumor,normal,0,67,"ENSG00000102048_bin0_[0.000,1.000): 1→-1; ENSG00000198963_bin0_[0.000,1.000): 1→-1; ENSG00000108684_bin0_[0.000,1.00..."
2,33,tumor,normal,0,67,"ENSG00000102048_bin0_[0.000,1.000): 1→-1; ENSG00000198963_bin0_[0.000,1.000): 1→-1; ENSG00000108684_bin0_[0.000,1.00..."

### `hyperlogic/brca-n` — règles (top 10)

,rule_id,if,then_class,score
0,36,"ENSG00000283321_bin0_[0.000,1.000)=+1 AND\nENSG00000124588_bin0_[0.000,1.000)=+1 AND\nENSG00000138347_bin0_[0.000,1.000)=-1 AND\nENSG00000152954_bin0_[0.000,1.000)=-1",tumor,0.973733
1,23,"ENSG00000143198_bin0_[0.000,1.000)=-1 AND\nENSG00000160145_bin0_[0.000,1.000)=-1 AND\nENSG00000050628_bin0_[0.000,1.000)=-1 AND\nENSG00000181722_bin0_[0.000,1.000)=-1",tumor,0.954364
2,12,"ENSG00000176769_bin0_[0.000,1.000)=+1 AND\nENSG00000175879_bin0_[0.000,1.000)=-1 AND\nENSG00000018510_bin0_[0.000,1.000)=-1 AND\nENSG00000113269_bin0_[0.000,1.000)=+1",tumor,0.939728
3,10,"ENSG00000176171_bin0_[0.000,1.000)=-1 AND\nENSG00000112293_bin0_[0.000,1.000)=-1 AND\nENSG00000143198_bin0_[0.000,1.000)=+1 AND\nENSG00000140807_bin0_[0.000,1.000)=-1",tumor,0.927847
4,28,"ENSG00000168702_bin0_[0.000,1.000)=+1 AND\nENSG00000138347_bin0_[0.000,1.000)=+1 AND\nENSG00000011198_bin0_[0.000,1.000)=-1 AND\nENSG00000283321_bin0_[0.000,1.000)=-1",normal,0.919598
5,1,"ENSG00000010310_bin0_[0.000,1.000)=-1 AND\nENSG00000185689_bin0_[0.000,1.000)=+1 AND\nENSG00000163285_bin0_[0.000,1.000)=-1 AND\nENSG00000204909_bin0_[0.000,1.000)=+1",tumor,0.914824
6,27,"ENSG00000112294_bin0_[0.000,1.000)=+1 AND\nENSG00000169877_bin0_[0.000,1.000)=-1 AND\nENSG00000064393_bin0_[0.000,1.000)=+1 AND\nENSG00000204909_bin0_[0.000,1.000)=+1",normal,0.902044
7,0,"ENSG00000164211_bin0_[0.000,1.000)=+1 AND\nENSG00000198963_bin0_[0.000,1.000)=+1 AND\nENSG00000115604_bin0_[0.000,1.000)=+1 AND\nENSG00000011198_bin0_[0.000,1.000)=-1",tumor,0.895959
8,13,"ENSG00000107938_bin0_[0.000,1.000)=+1 AND\nENSG00000198130_bin0_[0.000,1.000)=-1 AND\nENSG00000168702_bin0_[0.000,1.000)=-1 AND\nENSG00000164211_bin0_[0.000,1.000)=+1",normal,0.851722
9,15,"ENSG00000102359_bin0_[0.000,1.000)=-1 AND\nENSG00000113269_bin0_[0.000,1.000)=+1 AND\nENSG00000050628_bin0_[0.000,1.000)=+1 AND\nENSG00000176171_bin0_[0.000,1.000)=-1",tumor,0.836528

### `hyperlogic/brca-s` — mode `instance` — contrefactuels

,sample,pred,target,valid_cf,n_flips,flips
0,29,1,0,0,63,"ENSG00000104783_bin0_[0.000,1.000): 1→-1; ENSG00000136155_bin0_[0.000,1.000): 1→-1; ENSG00000128510_bin0_[0.000,1.00..."
1,29,1,2,0,62,"ENSG00000104783_bin0_[0.000,1.000): 1→-1; ENSG00000136155_bin0_[0.000,1.000): 1→-1; ENSG00000128510_bin0_[0.000,1.00..."
2,29,1,3,0,64,"ENSG00000104783_bin0_[0.000,1.000): 1→-1; ENSG00000136155_bin0_[0.000,1.000): 1→-1; ENSG00000159556_bin0_[0.000,1.00..."
3,1,1,0,0,63,"ENSG00000104783_bin0_[0.000,1.000): 1→-1; ENSG00000136155_bin0_[0.000,1.000): 1→-1; ENSG00000128510_bin0_[0.000,1.00..."
4,1,1,2,0,62,"ENSG00000104783_bin0_[0.000,1.000): 1→-1; ENSG00000136155_bin0_[0.000,1.000): 1→-1; ENSG00000128510_bin0_[0.000,1.00..."
5,1,1,3,0,64,"ENSG00000104783_bin0_[0.000,1.000): 1→-1; ENSG00000136155_bin0_[0.000,1.000): 1→-1; ENSG00000159556_bin0_[0.000,1.00..."
6,17,1,0,0,63,"ENSG00000104783_bin0_[0.000,1.000): 1→-1; ENSG00000136155_bin0_[0.000,1.000): 1→-1; ENSG00000128510_bin0_[0.000,1.00..."
7,17,1,2,0,62,"ENSG00000104783_bin0_[0.000,1.000): 1→-1; ENSG00000136155_bin0_[0.000,1.000): 1→-1; ENSG00000128510_bin0_[0.000,1.00..."
8,17,1,3,0,64,"ENSG00000104783_bin0_[0.000,1.000): 1→-1; ENSG00000136155_bin0_[0.000,1.000): 1→-1; ENSG00000159556_bin0_[0.000,1.00..."

### `hyperlogic/brca-s` — règles (top 10)

,rule_id,if,then_class,score
0,43,"ENSG00000229544_bin0_[0.000,1.000)=-1 AND\nENSG00000178372_bin0_[0.000,1.000)=-1 AND\nENSG00000177839_bin0_[0.000,1.000)=+1 AND\nENSG00000180999_bin0_[0.000,1.000)=-1",0,0.735646
1,11,"ENSG00000119812_bin0_[0.000,1.000)=-1 AND\nENSG00000084207_bin0_[0.000,1.000)=+1 AND\nENSG00000075618_bin0_[0.000,1.000)=-1 AND\nENSG00000168268_bin0_[0.000,1.000)=-1",3,0.708041
2,26,"ENSG00000143546_bin0_[0.000,1.000)=-1 AND\nENSG00000102900_bin0_[0.000,1.000)=-1 AND\nENSG00000198729_bin0_[0.000,1.000)=-1 AND\nENSG00000142700_bin0_[0.000,1.000)=+1",0,0.682496
3,52,"ENSG00000133019_bin0_[0.000,1.000)=-1 AND\nENSG00000135069_bin0_[0.000,1.000)=-1 AND\nENSG00000092621_bin0_[0.000,1.000)=+1 AND\nENSG00000099284_bin0_[0.000,1.000)=+1",2,0.662611
4,22,"ENSG00000136425_bin0_[0.000,1.000)=-1 AND\nENSG00000135916_bin0_[0.000,1.000)=-1 AND\nENSG00000105173_bin0_[0.000,1.000)=-1 AND\nENSG00000180999_bin0_[0.000,1.000)=+1",1,0.653920
5,13,"ENSG00000146386_bin0_[0.000,1.000)=-1 AND\nENSG00000135069_bin0_[0.000,1.000)=+1 AND\nENSG00000152977_bin0_[0.000,1.000)=+1 AND\nENSG00000136425_bin0_[0.000,1.000)=-1",3,0.621141
6,30,"ENSG00000119866_bin0_[0.000,1.000)=+1 AND\nENSG00000058335_bin0_[0.000,1.000)=+1 AND\nENSG00000102243_bin0_[0.000,1.000)=-1 AND\nENSG00000165125_bin0_[0.000,1.000)=-1",1,0.611506
7,36,"ENSG00000268089_bin0_[0.000,1.000)=-1 AND\nENSG00000124102_bin0_[0.000,1.000)=+1 AND\nENSG00000197106_bin0_[0.000,1.000)=+1 AND\nENSG00000188505_bin0_[0.000,1.000)=+1",0,0.592168
8,17,"ENSG00000137090_bin0_[0.000,1.000)=+1 AND\nENSG00000187527_bin0_[0.000,1.000)=-1 AND\nENSG00000133019_bin0_[0.000,1.000)=-1 AND\nENSG00000142700_bin0_[0.000,1.000)=-1",3,0.591663
9,21,"ENSG00000126878_bin0_[0.000,1.000)=-1 AND\nENSG00000124134_bin0_[0.000,1.000)=+1 AND\nENSG00000103546_bin0_[0.000,1.000)=-1 AND\nENSG00000099284_bin0_[0.000,1.000)=+1",2,0.591214

### `hyperlogic/cardio` — mode `instance` — contrefactuels

,sample,pred,target,valid_cf,n_flips,flips
0,9171,1,0,0,19,"age_bin1_[0.529,0.676): -1→1; age_bin2_[0.676,0.824): 1→-1; age_bin3_[0.824,1.000): -1→1; height_bin2_[0.560,0.585):..."
1,1285,1,0,0,17,"age_bin1_[0.529,0.676): -1→1; height_bin2_[0.560,0.585): 1→-1; weight_bin2_[0.323,0.376): -1→1; weight_bin3_[0.376,1..."
2,10808,0,1,1,15,"age_bin1_[0.529,0.676): -1→1; height_bin0_[0.000,0.528): 1→-1; weight_bin0_[0.000,0.286): 1→-1; weight_bin1_[0.286,0..."

### `hyperlogic/cardio` — règles (top 10)

,rule_id,if,then_class,score
0,34,"age_bin2_[0.676,0.824)=+1 AND\ngluc=3=+1 AND\nage_bin1_[0.529,0.676)=+1 AND\nap_hi_bin2_[0.018,1.000)=+1",1,0.999697
1,23,"height_bin1_[0.528,0.560)=-1 AND\ngender=1=-1 AND\nheight_bin3_[0.585,1.000)=+1 AND\ngender=2=+1",0,0.998256
2,21,"ap_lo_bin2_[0.014,1.000)=+1 AND\ngluc=3=+1 AND\nheight_bin2_[0.560,0.585)=+1 AND\nalco=1=+1",1,0.996279
3,32,"ap_lo_bin0_[0.000,0.014)=-1 AND\nalco=1=-1 AND\nsmoke=1=-1 AND\nap_lo_bin2_[0.014,1.000)=-1",0,0.991865
4,29,"smoke=1=+1 AND\ngluc=1=-1 AND\nage_bin2_[0.676,0.824)=-1 AND\nweight_bin0_[0.000,0.286)=-1",1,0.988931
5,25,"smoke=0=+1 AND\nactive=0=-1 AND\nheight_bin3_[0.585,1.000)=+1 AND\nweight_bin1_[0.286,0.323)=+1",1,0.987994
6,26,"height_bin3_[0.585,1.000)=-1 AND\ngluc=1=-1 AND\nweight_bin2_[0.323,0.376)=-1 AND\nalco=1=+1",0,0.986276
7,35,"age_bin3_[0.824,1.000)=-1 AND\nsmoke=0=-1 AND\nheight_bin3_[0.585,1.000)=+1 AND\ngluc=1=-1",1,0.983602
8,19,"age_bin2_[0.676,0.824)=+1 AND\ncholesterol=2=-1 AND\nalco=1=-1",1,0.982090
9,16,"weight_bin3_[0.376,1.000)=+1 AND\nap_hi_bin0_[0.000,0.017)=+1 AND\nweight_bin0_[0.000,0.286)=+1 AND\ngluc=2=+1",1,0.980500

### `hyperlogic/disease` — mode `instance` — contrefactuels

,sample,pred,target,valid_cf,n_flips,flips
0,644,39,0,0,67,symptom=acute_liver_failure: -1→1; symptom=altered_sensorium: -1→1; symptom=anxiety: -1→1; symptom=back_pain: -1→1; ...
1,644,39,1,0,68,symptom=acute_liver_failure: -1→1; symptom=altered_sensorium: -1→1; symptom=anxiety: -1→1; symptom=back_pain: -1→1; ...
2,644,39,2,0,65,symptom=acute_liver_failure: -1→1; symptom=altered_sensorium: -1→1; symptom=anxiety: -1→1; symptom=back_pain: -1→1; ...
3,644,39,3,0,69,symptom=acute_liver_failure: -1→1; symptom=altered_sensorium: -1→1; symptom=anxiety: -1→1; symptom=back_pain: -1→1; ...
4,644,39,4,0,65,symptom=acute_liver_failure: -1→1; symptom=altered_sensorium: -1→1; symptom=anxiety: -1→1; symptom=bladder_discomfor...
...,...,...,...,...,...,...
115,760,3,36,0,75,symptom=acidity: -1→1; symptom=altered_sensorium: -1→1; symptom=anxiety: -1→1; symptom=blackheads: -1→1; symptom=bla...
116,760,3,37,0,75,symptom=abdominal_pain: 1→-1; symptom=acidity: -1→1; symptom=altered_sensorium: -1→1; symptom=anxiety: -1→1; symptom...
117,760,3,38,0,72,symptom=acidity: -1→1; symptom=altered_sensorium: -1→1; symptom=anxiety: -1→1; symptom=blackheads: -1→1; symptom=bla...
118,760,3,39,0,77,symptom=abdominal_pain: 1→-1; symptom=acidity: -1→1; symptom=altered_sensorium: -1→1; symptom=anxiety: -1→1; symptom...
119,760,3,40,0,74,symptom=acidity: -1→1; symptom=altered_sensorium: -1→1; symptom=anxiety: -1→1; symptom=blackheads: -1→1; symptom=bla...

### `hyperlogic/disease` — règles (top 10)

,rule_id,if,then_class,score
0,68,symptom=extra_marital_contacts=-1 AND\nsymptom=dark_urine=-1 AND\nsymptom=burning_micturition=-1 AND\nsymptom=puffy_face_and_eyes=+1,26,0.309345
1,74,symptom=pain_during_bowel_movements=-1 AND\nsymptom=irritability=+1 AND\nsymptom=constipation=+1 AND\nsymptom=obesity=+1,11,0.297891
2,124,symptom=skin_rash=-1 AND\nsymptom=abnormal_menstruation=-1 AND\nsymptom=loss_of_smell=+1 AND\nsymptom=pain_during_bowel_movements=-1,35,0.282601
3,25,symptom=depression=+1 AND\nsymptom=dark_urine=-1 AND\nsymptom=loss_of_smell=+1 AND\nsymptom=irritation_in_anus=+1,33,0.281118
4,107,symptom=diarrhoea=+1 AND\nsymptom=irritability=+1 AND\nsymptom=receiving_unsterile_injections=-1 AND\nsymptom=coma=-1,26,0.268382
5,0,symptom=prominent_veins_on_calf=+1 AND\nsymptom=patches_in_throat=+1 AND\nsymptom=stomach_bleeding=-1 AND\nsymptom=skin_rash=-1,31,0.263220
6,33,symptom=indigestion=+1 AND\nsymptom=swollen_legs=+1 AND\nsymptom=coma=+1 AND\nsymptom=cold_hands_and_feets=+1,16,0.263135
7,121,symptom=diarrhoea=+1 AND\nsymptom=continuous_sneezing=-1 AND\nsymptom=muscle_pain=+1 AND\nsymptom=pus_filled_pimples=+1,28,0.260570
8,57,symptom=stiff_neck=+1 AND\nsymptom=back_pain=+1 AND\nsymptom=internal_itching=-1 AND\nsymptom=skin_rash=+1,33,0.253321
9,83,symptom=vomiting=-1 AND\nsymptom=weight_gain=-1 AND\nsymptom=history_of_alcohol_consumption=+1 AND\nsymptom=headache=-1,38,0.251302

## Comparaison rapide avec le notebook DR-HyperCF

Ce notebook utilise la **façade TabResNetDLBAC** :
- même cœur `HybridDRNetModel` en basse dimension ;
- bascule automatique vers **HyConEx bipolar + hyper TabResNet** si `n_features > 512` ;
- hyperparamètres calibrés DLBAC (température 0.7, CF warmup, early stop auto).

In [7]:
if runs:
    modes = pd.Series({k: v['result'].mode for k, v in runs.items()}).value_counts()
    print('Répartition des modes TabResNetDLBAC:')
    print(modes.to_string())

Répartition des modes TabResNetDLBAC:
instance    13